### ISSUE TITLE
[Bug report] @vuepress/plugin-google-analytics 构建失败

### ISSUE THREAD

**Issue by rich1e** [vuepress/vuepress-next#1007]
### Description

在本地运行 `yarn docs:build` 时，报错如下：

```
➜  ~ git:(main) ✗ yarn docs:build
yarn run v1.22.15
$ vuepress build docs
TypeError: Cannot read properties of undefined (reading 'isDev')
    at /Desktop/workspace/blog/node_modules/@vuepress/plugin-google-analytics/lib/node/googleAnalyticsPlugin.js:13:17
    at resolvePlugin (/Desktop/workspace/blog/node_modules/@vuepress/core/lib/app/resolvePlugin.js:18:11)
    at /Desktop/workspace/blog/node_modules/@vuepress/core/lib/app/resolvePluginsFromConfig.js:12:53
    at Array.reduce (<anonymous>)
    at resolvePluginsFromConfig (/Desktop/workspace/blog/node_modules/@vuepress/core/lib/app/resolvePluginsFromConfig.js:9:65)
    at createBaseApp (/Desktop/workspace/blog/node_modules/@vuepress/core/lib/app/createBaseApp.js:47:77)
    at createBuildApp (/Desktop/workspace/blog/node_modules/@vuepress/core/lib/app/createBuildApp.js:10:51)
    at /Desktop/workspace/blog/rich1e.me/node_modules/@vuepress/cli/lib/commands/build/createBuild.js:23:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

google-analytics 插件引入配置：

```js
export default defineUserConfig<DefaultThemeOptions, ViteBundlerOptions>({
  plugins: [
    [
      "vuepress-plugin-typescript",
      {
        tsLoaderOptions: {
          // ts-loader 的所有配置项
        },
      },
    ],
    [
      "@vuepress/plugin-google-analytics",
      {
        id: "G-XXXXXXXXXX",
      },
    ],
  ],
});
```

### Reproduction

https://github.com/rich1e/rich1e.github.io/runs/7625255719?check_suite_focus=true#step:6:21

https://github.com/vuepress/vuepress-next/blob/aa6e06dea8512b6c9ebb45c86a1f3694e0fce23b/packages/%40vuepress/plugin-google-analytics/src/node/googleAnalyticsPlugin.ts#L26

### Used Package Manager

yarn

### System Info

```shell
{
  "name": "poetry",
  "version": "1.0.0",
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "main": "index.js",
  "devDependencies": {
    "@vuepress/bundler-vite": "^2.0.0-beta.27",
    "@vuepress/plugin-container": "^2.0.0-beta.29",
    "@vuepress/plugin-google-analytics": "^2.0.0-beta.49",
    "@vuepress/plugin-toc": "^2.0.0-beta.27",
    "markdown-it-footnote": "^3.0.3",
    "transliteration": "^2.2.0",
    "typescript": "^4.5.4",
    "vuepress": "^2.0.0-beta.27",
    "vuepress-plugin-typescript": "^0.3.1"
  }
}
```

**Comment by youcanping** [comment]
"vuepress": "^2.0.0-beta.49", 
---------
// vuepress and plugins versions must match
"@vuepress/plugin-google-analytics": "^2.0.0-beta.49",
"vuepress": "^2.0.0-beta.49",
