### ISSUE TITLE
[Bug report] Error after using docsearch plugin: Uncaught (in promise) Error: useRouteLocale() is called without provider.

### ISSUE THREAD

**Issue by qiuxchao** [vuepress/vuepress-next#1015]
### Description

I have introduced the docsearch plugin in my vuepress project and configured it as per the official documentation, then I get some errors when I start my program:

```
Uncaught (in promise) Error: useRouteLocale() is called without provider.
    at useRouteLocale (chunk-OOQFWU6B.js:79:11)
    at setup (Docsearch.js:22:29)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5587:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)

Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
    at v (vendor.js:1:972874)

[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Docsearch options= {appId: 'xxx', apiKey: 'xxx', indexName: 'xxx', locales: {…}}apiKey: "xxx"appId: "xxx"indexName: "xxx"locales: {/zh/: {…}}[[Prototype]]: Object > 
  at <Docsearch> 
  at <NavbarSearch> 
  at <Navbar key=0 onToggleSidebar=fn<toggleSidebar> > 
  at <Layout> 
  at <AsyncComponentWrapper> 
  at <Vuepress onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <VuepressApp>
```

Please help me find the cause of the problem, thanks!

### Reproduction

https://github.com/qiuxchao/vuepress-issues-demo

### Used Package Manager

yarn

### System Info

```shell
System:
    OS: macOS 11.6.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 139.40 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Utilities:
    Git: 2.32.0 - /usr/bin/git
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.48 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.48 
    @vuepress/client:  2.0.0-beta.48 (2.0.0-beta.49)
    @vuepress/core:  2.0.0-beta.48 (2.0.0-beta.49)
    @vuepress/markdown:  2.0.0-beta.48 (2.0.0-beta.49)
    @vuepress/plugin-active-header-links:  2.0.0-beta.48 
    @vuepress/plugin-back-to-top:  2.0.0-beta.48 
    @vuepress/plugin-container:  2.0.0-beta.48 
    @vuepress/plugin-docsearch: ^2.0.0-beta.49 => 2.0.0-beta.49 
    @vuepress/plugin-external-link-icon:  2.0.0-beta.48 
    @vuepress/plugin-git:  2.0.0-beta.48 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.48 
    @vuepress/plugin-nprogress:  2.0.0-beta.48 
    @vuepress/plugin-palette:  2.0.0-beta.48 
    @vuepress/plugin-prismjs:  2.0.0-beta.48 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.48 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.48 (2.0.0-beta.49)
    @vuepress/theme-default:  2.0.0-beta.48 
    @vuepress/utils:  2.0.0-beta.48 (2.0.0-beta.49)
    vue:  3.2.37 
    vue-loader: Not Found
    vue-router:  4.0.16 (4.1.2)
    vuepress: ^2.0.0-beta.48 => 2.0.0-beta.48 
    vuepress-vite:  2.0.0-beta.48 
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
Use same version instead of mixing them, try using beta.49

**Comment by qiuxchao** [comment]
> 使用相同版本而不是混合它们，尝试使用 beta.49

It is indeed a version problem, thank you!
