### ISSUE TITLE
[Bug report] Uncaught (in promise) Error: useRouteLocale() is called without provider.

### ISSUE THREAD

**Issue by yuntian001** [vuepress/vuepress-next#1047]
### Description

When I use `@vuepress/plugin-search` :
```
chunk-V3MKNX2O.js?v=f3edc93b:89 Uncaught (in promise) Error: useRouteLocale() is called without provider.
    at useRouteLocale (chunk-V3MKNX2O.js?v=f3edc93b:89:11)
    at setup (SearchBox.js:27:29)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5587:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
```

### Reproduction

https://github.com/meadmin-cn/meadmin-template-doc

### Used Package Manager

npm

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 6.13 GB / 15.86 GB
  npmPackages:
    @vuepress/plugin-search: ^2.0.0-beta.50 => 2.0.0-beta.50
    vuepress: ^2.0.0-beta.50 => 2.0.0-beta.50
```

**Comment by meteorlxy** [comment]
Sorry but we could not find `plugin-search` in your repro repo, and the version is beta.49 - not beta.50

**Comment by yuntian001** [comment]
> Sorry but we could not find `plugin-search` in your repro repo, and the version is beta.49 - not beta.50

![image](https://user-images.githubusercontent.com/43692243/186597529-8f39de32-2d2c-45a8-a465-5c19b7771191.png)
![image](https://user-images.githubusercontent.com/43692243/186597621-1db5689e-9747-46fd-a205-629419f49f1e.png)
