### ISSUE TITLE
[Bug report] 我应该怎么 debug 这个东西？

### ISSUE THREAD

**Issue by ice1000** [vuepress/vuepress-next#1066]
### Description

我现在执行 `npm run build` 也就是 `vuepress build src` 的时候遇到了这个报错:

```
~/git-repos/aya-prover-docs (main) λ> npm run build

> aya-prover-docs@1.0.0 build
> vuepress build src

✔ Initializing and preparing data - done in 1.46s
⠧ Compiling with viteError when using sourcemap for reporting an error: Can't resolve original location of error.
'default' is not exported by src/.vuepress/.temp/pages/index.html.vue?vue&type=div&index=0&lang.div, imported by src/.vuepress/.temp/pages/index.html.vue
file: /home/ice/git-repos/aya-prover-docs/src/.vuepress/.temp/pages/index.html.vue:4:7
2:
3:
4: import block0 from "/home/ice/git-repos/aya-prover-docs/src/.vuepress/.temp/pages/index.html.vue?vue&type=div&index=0&lang.div"
          ^
5: if (typeof block0 === 'function') block0(_sfc_main)
✖ Compiling with vite - failed in 2.66s
Error: 'default' is not exported by src/.vuepress/.temp/pages/index.html.vue?vue&type=div&index=0&lang.div, imported by src/.vuepress/.temp/pages/index.html.vue
    at error (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12412:16)
    at Module.traceVariable (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12771:29)
    at ModuleScope.findVariable (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11423:39)
    at Identifier.bind (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7422:40)
    at UnaryExpression.bind (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at BinaryExpression.bind (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at IfStatement.bind (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at Program.bind (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5248:73)
    at Module.bindReferences (file:///home/ice/git-repos/aya-prover-docs/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12408:18)
```

我查了很久，网上众说纷纭，但我觉得我这个问题的根本原因可能是因为我的 `src/.vuepress/.temp/pages/index.html.vue` 的内容是如下的:

```
undefined<div>undefined</div>undefined


```

我希望了解如何调试 vuepress 以及我到底是做错了什么。我个人不熟前端，所以希望开发者们能对我耐心一点，我会尽可能提供开发环境相关的信息，谢谢了。

### Reproduction

https://github.com/aya-prover/aya-prover-docs

### Used Package Manager

npm

### System Info

```shell
这是 `vuepress info` 的输出，我觉得可能这不是环境信息。我用的 vuepress 小版本号是 51，环境是 Ubuntu WSL。


~/git-repos/aya-prover-docs (main) λ> npm run info

> aya-prover-docs@1.0.0 info
> vuepress info

⠋ Collecting Environment InfoTypeError: envinfo.run is not a function
    at info (file:///home/ice/git-repos/aya-prover-docs/node_modules/@vuepress/cli/dist/index.js:525:32)
    at CAC.wrappedCommand (file:///home/ice/git-repos/aya-prover-docs/node_modules/@vuepress/cli/dist/index.js:584:39)
    at CAC.runMatchedCommand (file:///home/ice/git-repos/aya-prover-docs/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///home/ice/git-repos/aya-prover-docs/node_modules/cac/dist/index.mjs:537:12)
    at cli (file:///home/ice/git-repos/aya-prover-docs/node_modules/@vuepress/cli/dist/index.js:602:11)
    at file:///home/ice/git-repos/aya-prover-docs/node_modules/vuepress/node_modules/vuepress-vite/bin/vuepress.js:8:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
```
```

**Comment by ice1000** [comment]
项目原本是 vuepress 1，我在往 2 迁移

**Comment by meteorlxy** [comment]
你没有提供 lock 文件。另外提问请移步 Discussion
