### ISSUE TITLE
[Bug report] Cannot find package '@internal/pagesData'

### ISSUE THREAD

**Issue by confused-Techie** [vuepress/vuepress-next#1089]
### Description

When using `vuepress: 2.0.0-beta.51` we are experiencing this issue during GitHub actions.

The full output we are receiving is below:

```shell
Run yarn docs:build
yarn run v1.22.19
$ vuepress build docs
info Initializing VuePress and preparing data...
- Compiling with vite
✔ Compiling with vite - done
- Rendering pages
✖ Rendering pages - failed
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/pagesData' imported from /home/runner/work/pulsar-edit.github.io/pulsar-edit.github.io/node_modules/@vuepress/client/dist/chunk-V3MKNX2O.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:[4](https://github.com/pulsar-edit/pulsar-edit.github.io/actions/runs/3065960717/jobs/4950609142#step:5:5)0)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:7[5](https://github.com/pulsar-edit/pulsar-edit.github.io/actions/runs/3065960717/jobs/4950609142#step:5:6):3[6](https://github.com/pulsar-edit/pulsar-edit.github.io/actions/runs/3065960717/jobs/4950609142#step:5:7))
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Prior to receiving this exact issue, we were getting errors seeming to relate to missing `type: module` within `package.json` and after adding it, this was the next error. So its possible they may be somehow related?

But never-the-less here are some relevant links to this issue:

* [GitHub Action Where it is Occuring](https://github.com/pulsar-edit/pulsar-edit.github.io/actions/runs/3065960717/jobs/4950609142)
* [Original Issue Creating leading to this error](https://github.com/pulsar-edit/pulsar-edit.github.io/issues/15)
* [PR With attempted fixes (Among other things)](https://github.com/pulsar-edit/pulsar-edit.github.io/pull/16)
* [PR Where the issue originally began, that was merged before this was caught](https://github.com/pulsar-edit/pulsar-edit.github.io/pull/10)
* [Issue Opened here from 2.0.0-beta.42](https://github.com/vuepress/vuepress-next/issues/1083)

### Reproduction

https://github.com/pulsar-edit/pulsar-edit.github.io

### Used Package Manager

yarn

### System Info

```shell
Unfortunately as this is a GitHub Action obtaining this info is difficult. But:

* Node: 14
* vuepress: 2.0.0-beta.51
```

**Comment by Mister-Hope** [comment]
> Prior to receiving this exact issue, we were getting errors seeming to relate to missing type: module within package.json and after adding it, this was the next error. So its possible they may be somehow related?

I am not seeing `type: module` in your package.json

**Comment by Mister-Hope** [comment]
https://github.com/pulsar-edit/pulsar-edit.github.io/blob/77d38b61e770685102b0153fa7a082c2757c68f6/yarn.lock#L271
You are using beta.50-pre. Use beta.51

**Comment by Mister-Hope** [comment]
@meteorlxy  I am seeing much more users like this in my user group. beta.50-pre is a terrible version tag, as this is greater then any version like `2.0.0-beta.xx`. Can we manage to fix this? Like moving on to a new prefix?

**Comment by confused-Techie** [comment]
@Mister-Hope thanks for the help! I didn't realize that in our `yarn.lock` file it was installing an older version, since the `package.json` specified beta.51

But sure enough one `yarn upgrade vuepress@2.0.0-beta.51` got it to install the proper version, and the builds are working now. Thanks a ton
