### ISSUE TITLE
[Bug report] Anchor placement setting doesn't take effect

### ISSUE THREAD

**Issue by Marerc** [vuepress/vuepress-next#1109]
### Description

set `markdown.anchor.permalink = anchorPlugin.permalink.ariaHidden({placement: "after"})`    

however the anchor sign still before the title.

### Reproduction

https://stackblitz.com/edit/vuepress-qj4asr

### Used Package Manager

npm

### System Info

```shell
Collecting Environment InfoTypeError: envinfo.run is not a function
    at info (file:///home/projects/vuepress-qj4asr/node_modules/@vuepress/cli/dist/index.js:548:32)
    at CAC.wrappedCommand (file:///home/projects/vuepress-qj4asr/node_modules/@vuepress/cli/dist/index.js:607:39)
    at CAC.runMatchedCommand (file:///home/projects/vuepress-qj4asr/node_modules/cac/dist/index.mjs:628:34)
    at CAC.parse (file:///home/projects/vuepress-qj4asr/node_modules/cac/dist/index.mjs:555:12)
    at Module.cli (file:///home/projects/vuepress-qj4asr/node_modules/@vuepress/cli/dist/index.js:625:11)
    at eval (file:///home/projects/vuepress-qj4asr/node_modules/vuepress-vite/bin/vuepress.js:17:15)
    at Generator.next (<anonymous>)
    at _0x3ce0dd.run (https://vuepress-qj4asr.w.staticblitz.com/blitz.3d5b7ec3447d031d69874de6ce8da2d6e817b468.js:15:287784)
    at _0x4ea9cf._evaluate (https://vuepress-qj4asr.w.staticblitz.com/blitz.3d5b7ec3447d031d69874de6ce8da2d6e817b468.js:15:293129)
    at async _0x4ea9cf._evaluate (https://vuepress-qj4asr.w.staticblitz.com/blitz.3d5b7ec3447d031d69874de6ce8da2d6e817b468.js:15:293035)
```

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/192964430-6e13a4bf-3d1a-4980-a614-324747257c97.png)

The anchor plugin is working as expected. What you are missing is that you are expected to adjust the styles yourself.

**Comment by Marerc** [comment]
> ![image](https://user-images.githubusercontent.com/33315834/192964430-6e13a4bf-3d1a-4980-a614-324747257c97.png)
> 
> The anchor plugin is working as expected. What you are missing is that you are expected to adjust the styles yourself.

Yep, after setting float attribution to `unset`, it works properly, but why should additional step be taken, the `placement` option itself should done the style setting so that this attribution is semantic correct, and easy to be understand.
