### ISSUE TITLE
[Bug report] TOC show the variant name rather than the value it represents when use frontmatter variant.

### ISSUE THREAD

**Issue by Marerc** [vuepress/vuepress-next#1124]
### Description

![image](https://user-images.githubusercontent.com/14820859/194812104-eda8b036-e704-4fba-b2e2-6bdaeac249de.png)

### Reproduction

https://stackblitz.com/edit/vuepress-njrtap

### Used Package Manager

npm

### System Info

```shell
nothing but an error message. 

❯ vuepress info
⠋ Collecting Environment InfoTypeError: envinfo.run is not a function
    at info (file:///home/projects/vuepress-njrtap/node_modules/@vuepress/cli/dist/index.js:548:32)
    at CAC.wrappedCommand (file:///home/projects/vuepress-njrtap/node_modules/@vuepress/cli/dist/index.js:607:39)
    at CAC.runMatchedCommand (file:///home/projects/vuepress-njrtap/node_modules/cac/dist/index.mjs:628:34)
    at CAC.parse (file:///home/projects/vuepress-njrtap/node_modules/cac/dist/index.mjs:555:12)
    at Module.cli (file:///home/projects/vuepress-njrtap/node_modules/@vuepress/cli/dist/index.js:625:11)
    at eval (file:///home/projects/vuepress-njrtap/node_modules/vuepress-vite/bin/vuepress.js:17:15)
    at Generator.next (<anonymous>)
    at _0x1a557c.run (https://vuepress-njrtap.w.staticblitz.com/blitz.c3f3eab0760382367e86f2a862c18516376c36f4.js:15:289226)
    at _0x5424d8._evaluate (https://vuepress-njrtap.w.staticblitz.com/blitz.c3f3eab0760382367e86f2a862c18516376c36f4.js:15:294625)
    at async _0x5424d8._evaluate (https://vuepress-njrtap.w.staticblitz.com/blitz.c3f3eab0760382367e86f2a862c18516376c36f4.js:15:294524)
```

**Comment by Mister-Hope** [comment]
Expected, we only support Vue grammar in `<Content />`, i.e.: the main content of page.
