### ISSUE TITLE
[Bug report] Markdown with component imported randomesly failed during built

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#1147]
### Description

When uses import componts in markdown files, e.g.:

```md
<MyComponent>

<script setup>
import MyComponent from '@MyComponent'
</script>
```

They may failed with the following issue randomly.

Logs:

```
docs/theme docs:vite-build: ✔ Initializing and preparing data - done in 35.96s
docs/theme docs:vite-build: - Compiling with vite
docs/theme docs:vite-build: [vite:esbuild] Transform failed with 1 error:
docs/theme docs:vite-build: /home/runner/work/vuepress-theme-hope/vuepress-theme-hope/docs/theme/src/.vuepress/.temp/pages/guide/interface/darkmode.html.vue?vue&type=script&setup=true&lang.ts:1:21: ERROR: Expected ";" but found "dark"
docs/theme docs:vite-build: file: /home/runner/work/vuepress-theme-hope/vuepress-theme-hope/docs/theme/src/.vuepress/.temp/pages/guide/interface/darkmode.html.vue?vue&type=script&setup=true&lang.ts:1:21
docs/theme docs:vite-build: 
docs/theme docs:vite-build: Expected ";" but found "dark"
docs/theme docs:vite-build: 1  |  <template><div><p>In dark mode, the page uses a dark background to make you comfortable.</p>
docs/theme docs:vite-build:    |                       ^
docs/theme docs:vite-build: 2  |  <!-- more -->
docs/theme docs:vite-build: 3  |  <h2 id="try-it" tabindex="-1"><a class="header-anchor" href="#try-it" aria-hidden="true">#</a> Try it</h2>
docs/theme docs:vite-build: 
docs/theme docs:vite-build: ✖ Compiling with vite - failed in 21.55s
docs/theme docs:vite-build: Error: Transform failed with 1 error:
docs/theme docs:vite-build: /home/runner/work/vuepress-theme-hope/vuepress-theme-hope/docs/theme/src/.vuepress/.temp/pages/guide/interface/darkmode.html.vue?vue&type=script&setup=true&lang.ts:1:21: ERROR: Expected ";" but found "dark"
docs/theme docs:vite-build:     at failureErrorWithLog (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:1566:15)
docs/theme docs:vite-build:     at /home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:805:29
docs/theme docs:vite-build:     at responseCallbacks.<computed> (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:671:9)
docs/theme docs:vite-build:     at handleIncomingPacket (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:726:9)
docs/theme docs:vite-build:     at Socket.readFromStdout (/home/runner/work/vuepress-theme-hope/vuepress-theme-hope/node_modules/.pnpm/esbuild@0.15.12/node_modules/esbuild/lib/main.js:647:7)
docs/theme docs:vite-build:     at Socket.emit (node:events:513:28)
docs/theme docs:vite-build:     at addChunk (node:internal/streams/readable:324:12)
docs/theme docs:vite-build:     at readableAddChunk (node:internal/streams/readable:297:9)
docs/theme docs:vite-build:     at Readable.push (node:internal/streams/readable:234:10)
docs/theme docs:vite-build:     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
docs/theme docs:vite-build: Failed
```

All problems logs are with same issue stack (the only difference is the first one comming from vue component converting from markdown, saying:

```
Expected ";" but found "<A word in markdown>"
```

@meteorlxy This happens after migrating to ESM.

## Posible reasons

I think we might need to double check if we have async task here that may excute in unexpected squence during build.

I already met this issue more that 30 times, with a probability around 10% - 20%.

**Comment by meteorlxy** [comment]
Be professional, boy. Report things "Mysteriously" is bad.

**Comment by Mister-Hope** [comment]
But with same code, ci fails sometimes and the only thing a get are those logs.


I have no idea how it happens because I am not be able to make a stable reproduction.

The only thing I guess is that there are some async process may causes some issue

**Comment by Mister-Hope** [comment]
I understand that this might be hard to debug, but this is not the first time I met them in ci.

**Comment by Mister-Hope** [comment]
A exmaple ：

https://github.com/vuepress-theme-hope/vuepress-theme-hope/actions/runs/3650362766/jobs/6174680253

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/33315834/206622320-a0ae7933-e792-41be-9ddd-50fc3917e4e2.png">

Neify and gitee workflow only differs 2 env  `process.env.base` and `process.env.hostname`。

I ensure this problem is not in my code and all the failed pages are not the same but all import vue component with `<script setup>`

**Comment by Mister-Hope** [comment]
I am not seeing this issue for quite a long time, closing it.

Guess the issue is from tool chain.
