### ISSUE TITLE
[Bug report] I can't run build  command.

### ISSUE THREAD

**Issue by Moon-18** [vuepress/vuepress-next#1288]
### Description

I can run dev command and I can see web pages in real time, but I can't run build  command.
Looking forward to your help
```
PS D:\Code\Web\RYBlog> pnpm build

> RYBlog@1.0.0 build D:\Code\Web\RYBlog
> vuepress build docs

✔ Initializing and preparing data - done in 5.19s
⠴ Compiling with vite[commonjs--resolver] Invalid URL
✖ Compiling with vite - failed in 997ms
TypeError [PLUGIN_ERROR]: Invalid URL
    at new NodeError (node:internal/errors:387:5)
    at URL.onParseError (node:internal/url:565:9)
    at parse (<anonymous>)
    at new URL (node:internal/url:641:5)
    at Object.resolveId (file:///D:/Code/Web/RYBlog/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:14757:25)
    at Object.handler (file:///D:/Code/Web/RYBlog/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44872:19)
    at file:///D:/Code/Web/RYBlog/node_modules/.pnpm/rollup@3.20.0/node_modules/rollup/dist/es/shared/node-entry.js:24349:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Code/Web/RYBlog/node_modules/.pnpm/rollup@3.20.0/node_modules/rollup/dist/es/shared/node-entry.js:24249:28)
    at async resolveId (file:///D:/Code/Web/RYBlog/node_modules/.pnpm/rollup@3.20.0/node_modules/rollup/dist/es/shared/node-entry.js:23186:26)
    at async ModuleLoader.resolveId (file:///D:/Code/Web/RYBlog/node_modules/.pnpm/rollup@3.20.0/node_modules/rollup/dist/es/shared/node-entry.js:23450:15)
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

https://github.com/Moon-18/RYBlog

### Used Package Manager

pnpm

### System Info

```shell
PS D:\Code\Web> vuepress info

Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
  Binaries:
    Node: 16.18.1 - D:\environment\nodejs\node.EXE
    Yarn: 1.22.19 - D:\environment\nodejs\yarn.CMD
    npm: 8.19.2 - D:\environment\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (111.0.1661.51)
  npmPackages:
    @vuepress/core: Not Found
    @vuepress/theme-default: Not Found
    vuepress: Not Found
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by Mister-Hope** [comment]
Provide a mininal reproduction

**Comment by Moon-18** [comment]
Sorry, but it looks like awebp format images cannot be supported, referenced images must exist, and the relative path format must start with./ not directly with the file name. Let me try it again, sorry to bother you
