### ISSUE TITLE
Behavior of filename containing `:`

### ISSUE THREAD

**Issue by rcrane** [vuepress/vuepress-next#1293]
### Clear and concise description of the problem

I'm am not sure if this is an NPM or Vuepress issue!

The compilation fails after adding a file with an arguably tricky name "2023-03-28T11:56:34+02:00.md" to the docs folder.
The error message does not indicate where the error occurs and that compilation failed due to the file name:

``` bash
npm run docs:build
```

``` text
Error: ERR (1)/"34": A repeatable param (34) must be alone in its segment. eg: '/:ids+.
    at crash (file:///build/node_modules/vue-router/dist/vue-router.mjs:1092:15)
    at consumeBuffer (file:///build/node_modules/vue-router/dist/vue-router.mjs:1126:17)
    at tokenizePath (file:///build/node_modules/vue-router/dist/vue-router.mjs:1178:21)
    at createRouteRecordMatcher (file:///build/node_modules/vue-router/dist/vue-router.mjs:1225:35)
    at addRoute (file:///build/node_modules/vue-router/dist/vue-router.mjs:1318:23)
    at file:///build/node_modules/vue-router/dist/vue-router.mjs:1486:29
    at Array.forEach (<anonymous>)
    at createRouterMatcher (file:///build/node_modules/vue-router/dist/vue-router.mjs:1486:12)
    at createRouter (file:///build/node_modules/vue-router/dist/vue-router.mjs:2942:21)
    at createVueRouter (file:///build/docs/.vuepress/.temp/.server/app.00b70600.mjs:3677:18)
```

* The compilation failure is not caused by the content of the file.
* From the error message, it is not clear what the issue is.
* Some sort of interpretation seems to be executed on the file name.(??)
* Changing the file name to "2023-03-28T11:5634+02:00.md" works. 
* The issue occurs if the name contains `:XX+`.
* ```DEBUG=vuepress*``` does not provide more/better insight.

### Suggested solution

A file handling routine that rejects troublesome files during compilation with a proper message or a trace that points to the file name as the issue.
Maybe a pre-compilation sanity check would be in order.

### Alternative

I could not find any information about valid file names in the documentation.
A short 'what-not-to-use' as name would be helpful as well.

**Comment by Mister-Hope** [comment]
: has special meaning with vue-router, see it's own docs

**Comment by rcrane** [comment]
Thanks!
Having successfully used Vuepress 1.9.2 before with these filenames, I just didn't know about the issue with ":".

I actually haven't been aware of vue-router and it's doc. Sorry for that.

Would adding "Filename to route conversion error." to the error message be an option?

**Comment by Mister-Hope** [comment]
The error is throwing at vue-router side, which is not our problem, and we are keeping them as is, in case someone really want a path like `/example/:id`

**Comment by meteorlxy** [comment]
Make we can add a tip in our docs, with a reference link to vue-router.
