### ISSUE TITLE
[Bug report]  Initializing and preparing dataerror error in hook clientConfigFile from vuepress-plugin-md-enhance

### ISSUE THREAD

**Issue by enjoy-rabbit520** [vuepress/vuepress-next#1441]
### Description

Require stack:
- D:\noteWebsite\my-notes\node_modules\vuepress-plugin-md-enhance\lib\node\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at cr (file:///D:/noteWebsite/my-notes/node_modules/vuepress-shared/lib/node/index.js:3:32208)
    at fn (file:///D:/noteWebsite/my-notes/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:63:3689)
    at clientConfigFile (file:///D:/noteWebsite/my-notes/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:89:2859)
    at Object.hook (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:728:60)
    at Object.process (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:681:37)
    at async prepareClientConfigs (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:3:29)
    at async appPrepare (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:623:3)
    at async file:///D:/noteWebsite/my-notes/node_modules/@vuepress/cli/dist/index.js:488:7

### Reproduction

https://blog-img-store1.oss-cn-guangzhou.aliyuncs.com/img/image-20231130105313401.png

### Used Package Manager

npm

### System Info

```shell
Require stack:
- D:\noteWebsite\my-notes\node_modules\vuepress-plugin-md-enhance\lib\node\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function.resolve (node:internal/modules/helpers:187:19)
    at cr (file:///D:/noteWebsite/my-notes/node_modules/vuepress-shared/lib/node/index.js:3:32208)
    at fn (file:///D:/noteWebsite/my-notes/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:63:3689)
    at clientConfigFile (file:///D:/noteWebsite/my-notes/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:89:2859)
    at Object.hook (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:728:60)
    at Object.process (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:681:37)
    at async prepareClientConfigs (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:3:29)
    at async appPrepare (file:///D:/noteWebsite/my-notes/node_modules/@vuepress/core/dist/index.js:623:3)
    at async file:///D:/noteWebsite/my-notes/node_modules/@vuepress/cli/dist/index.js:488:7
```

**Comment by Mister-Hope** [comment]
Solve the above issue one by one
