### ISSUE TITLE
[Bug report]

### ISSUE THREAD

**Issue by maodou38** [vuepress/vuepress-next#186]
### Description

markdown文件中有html标签，如&lt;font&gt;时，生成html页面报错

### Steps to reproduce

写一个带<font>标签的页面，使用2.X的vuepress生成页面

- Reproduction link / repo:
   https://github.com/roiding/roiding.github.io 中例如 docs\docker\docker-app.md中就有&lt;font&gt;标签

### Expected behavior

生成报错，已排除markdown-it问题，拷贝md文本至markdown-it.js页面正常展示

### Screenshots

![image](https://user-images.githubusercontent.com/39987981/120577206-93c00a80-c456-11eb-8f22-8dc925112ee6.png)

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here

warning plugin @vuepress/plugin-back-to-top has been used multiple times, only the last one will take effect
info Initializing VuePress and preparing data...
- Compiling with webpack
✔ Compiling with webpack - done
- Rendering pages
- Rendering pages /
- Rendering pages /attention.html
- Rendering pages /resource.html
- Rendering pages /docker/attention.html
- Rendering pages /docker/docker-app.html
✖ Rendering pages - failed
TypeError: Cannot create property '__props' on string 'font'
    at normalizePropsOptions (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:1386:30)
    at createComponentInstance (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5283:23)
    at renderComponentVNode (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:156:22)
    at ssrRenderComponent (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:481:12)
    at ssrRender (/home/runner/work/roiding.github.io/roiding.github.io/docs/.vuepress/dist/.server/646.app.js:322:48)
    at script.ssrRender (/home/runner/work/roiding.github.io/roiding.github.io/docs/.vuepress/dist/.server/646.app.js:363:10)
    at renderComponentSubTree (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:219:13)
    at renderComponentVNode (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:170:16)
    at renderVNode (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:260:22)
    at renderComponentSubTree (/home/runner/work/roiding.github.io/roiding.github.io/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:225:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ docs:build: `vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-03T02_18_57_169Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by maodou38** [comment]
实测将<font>标签去除，该页面就可正常生成

**Comment by maodou38** [comment]
如果不是bug，就请告诉我该怎么改才能不报错生成出红字。不要直接关闭好嘛。

**Comment by meteorlxy** [comment]
It's a breaking change of vue3.

In vue2:

https://codesandbox.io/s/vigilant-diffie-l80j9?file=/src/App.vue

In vue3 (check the console):

https://codesandbox.io/s/strange-chaum-erocj?file=/src/App.vue

---

> 不要直接关闭好嘛。

直接关闭是因为你不按照模板乱发 issue

**Comment by maodou38** [comment]
谢谢解答
