### ISSUE TITLE
[Bug report] 'TypeError: Invalid value used as weak map key' caused by <font:>

### ISSUE THREAD

**Issue by hust-whw** [vuepress/vuepress-next#201]
### Description

I use the `<font>` HTML  mark in the markdown file, when I did `vuepress dev docs` it run fine, however, when I did `vuepress build dosc` it showed the error below.

### Output:

```bash
# Paste output of `vuepress info` here
yarn run v1.22.10
$ vuepress build docs
info Initializing VuePress and preparing data...
✔ Compiling with webpack - done
✖ Rendering pages - failed
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/hustwhw/Desktop/Hustwhw/molewiki/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2760:15)
    at createComponentInstance (/Users/hustwhw/Desktop/Hustwhw/molewiki/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5521:23)
    at renderComponentVNode (/Users/hustwhw/Desktop/Hustwhw/molewiki/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:156:22)
    at ssrRenderComponent (/Users/hustwhw/Desktop/Hustwhw/molewiki/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:484:12)
    at ssrRender (/Users/hustwhw/Desktop/Hustwhw/molewiki/docs/.vuepress/dist/.server/669.app.js:68:48)
    at script.ssrRender (/Users/hustwhw/Desktop/Hustwhw/molewiki/docs/.vuepress/dist/.server/669.app.js:91:10)
    at renderComponentSubTree (/Users/hustwhw/Desktop/Hustwhw/molewiki/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:222:13)
    at renderComponentVNode (/Users/hustwhw/Desktop/Hustwhw/molewiki/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:173:16)
    at renderVNode (/Users/hustwhw/Desktop/Hustwhw/molewiki/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:263:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by meteorlxy** [comment]
Duplicated of #186

As that issue was not written in English, I just paste the answer here again.

---

It's a breaking change of vue3.

In vue2:

codesandbox.io/s/vigilant-diffie-l80j9?file=/src/App.vue

In vue3 (check the console):

codesandbox.io/s/strange-chaum-erocj?file=/src/App.vue

**Conclusion**

`<font>` element has been deprecated, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font. It would not be recognized as a native HTML tag correctly by vue.

If you want to use it anyway, register a custom component for that.
