### ISSUE TITLE
VueCompilerError: Single file component can contain only one <script> element

### ISSUE THREAD

**Issue by jinrongni** [vuepress/vuepress-next#299]
### Description

use more than one `<script></script>` or `<script setup></script>`  in  the xxx.md file then i got those error

### Steps to reproduce

jsut using two` script` tag  in a md file like this:
```js

<script>
console.log(1111)
</script>

<script>
console.log(1111)
</script>
```
- Reproduction link / repo:

### Expected behavior
no compilering error

### Screenshots
![image](https://user-images.githubusercontent.com/41502851/126634344-b7f0ddb6-8245-4829-8c07-3fe6a1f2c2b5.png)

### Environment info

- Browser: edge 91.0.864.71 
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
ERROR in ./docs/.vuepress/.temp/pages/components/modal.html.vue
Module Error (from ./node_modules/vue-loader/dist/index.js):

VueCompilerError:
VueCompilerError: Single file component can contain only one <script> element
at D:\group\eslink-ui-plus\docs\.vuepress\.temp\pages\components\modal.html.vue:75:1
72 |  console.log(1111)
73 |  </script>
74 |
   |   ^
75 |  <script>
   |  ^^^^^^^^
76 |  console.log(1111)
   |  ^^^^^^^^^^^^^^^^^
77 |  </script>
   |  ^^^^^^^^^

at D:\group\eslink-ui-plus\docs\.vuepress\.temp\pages\components\modal.html.vue:75:1
72 |  console.log(1111)
73 |  </script>
74 |
   |   ^
75 |  <script>
   |  ^^^^^^^^
76 |  console.log(1111)
   |  ^^^^^^^^^^^^^^^^^
77 |  </script>
   |  ^^^^^^^^^

webpack compiled with 1 error
info page components\modal.md is modified
```

**Comment by xwwei** [comment]
I had the same problem

**Comment by meteorlxy** [comment]
Markdown in VuePress will be converted to Vue SFC, so you should follow the rules of Vue SFC

**Comment by jinrongni** [comment]
> Markdown in VuePress will be converted to Vue SFC, so you should follow the rules of Vue SFC

I use vuepress for vue3 components library

I  need to write usage of the component like this 
```
# ESModal 模态框

## 基础用法
:::demo
<es-button @click="show = true" type="text">打开模态框</es-button>
<es-modal
	title="新建一个"
	cancelText="自定义的取消文案"
	confirmText="自定义的确认文案"
	:message="message"
	v-model="show"
>
	<es-button @click="show2 = true" type="text">
		点击打开又一个模态框,关闭时延时1s
	</es-button>
	<es-modal
		:message="message"
		v-model="show2"
		:append-to-body="true"
		:before-close="handleClose"
	>
		延迟1s关闭
	</es-modal>
</es-modal>

<script>
import { ref,defineComponent } from "vue"
export default defineComponent({
	setup(){
		const show = ref(false)
		const show2 = ref(false)
		const message = "延迟1s关闭"
		const handleClose = (close) => {
			setTimeout(close,1000)
		}
		return {
			show,
			show2,
			message,
			handleClose
		}
	}
})
</script>
:::

## 使用插槽

:::demo
<es-button @click="show = true" type="text">使用头部插槽</es-button>
<br />
<es-button @click="show1 = true" type="text">使用内容区插槽</es-button>
<br />
<es-button @click="show2 = true" type="text">使用底部区插槽</es-button>
<br />
<es-modal :message="message" v-model="show">
	<template #header>使用头部插槽</template>
</es-modal>
<es-modal title="提示" :message="message1" v-model="show1">
	<template #default>使用内容区插槽</template>
</es-modal>
<es-modal title="提示" :message="message2" v-model="show2">
	<template #footer>使用底部区插槽</template>
</es-modal>

<script>
	import { ref,defineComponent } from "vue"
	export default defineComponent({
		setup(){
			const show = ref(false)
			const show1 = ref(false)
			const show2 = ref(false)
			const message = ref( '使用头部插槽了')
			const message1 = ref( '使用内容区插槽了')
			const message2 = ref( '使用底部区插槽了')
			return {
				show,
				show1,
				show2,
				message,
				message1,
				message2,
			}
		}
	})
</script>
:::
```

Is there any way for me to use more than one script in a md file

**Comment by lyh0371** [comment]
Is this issue resolved？（这个问题有解决方案了吗？）
