### ISSUE TITLE
[Bug report] Build error

### ISSUE THREAD

**Issue by Mbensler** [vuepress/vuepress-next#304]
## Bug report

When trying to build vuepress I am receiving this error.  Dev mode works just fine.

### Description

```js

$ vuepress build docs
info Initializing VuePress and preparing data...
⠹ Compiling with vite[commonjs] Unexpected token (37:64) in C:/Users/mbe/Documents/dev/botassist_docs/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js
file: C:/Users/mbe/Documents/dev/botassist_docs/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:37:64
35:     parentNode: node => node.parentNode,
36:     nextSibling: node => node.nextSibling,
37:     querySelector: selector => doc.querySelector(selector),
                                                                ^
38:     setScopeId(el, id) {
39:         el.setAttribute(id, '');
✖ Compiling with vite - failed
SyntaxError: Unexpected token (37:64) in C:/Users/mbe/Documents/dev/botassist_docs/node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js
    at Parser.pp$4.raise (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:16935:13)
    at Parser.pp.unexpected (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14443:8)
    at Parser.pp.expect (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14437:26)
    at Parser.pp$3.parseObj (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:16549:12)
    at Parser.pp$3.parseExprAtom (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:16288:17)
    at Parser.pp$3.parseExprSubscripts (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:16107:19)
    at Parser.pp$3.parseMaybeUnary (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:16073:17)
    at Parser.pp$3.parseExprOps (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:16006:19)
    at Parser.pp$3.parseMaybeConditional (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:15989:19)
    at Parser.pp$3.parseMaybeAssign (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:15957:19)
    at Parser.pp$1.parseVar (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14984:24)
    at Parser.pp$1.parseVarStatement (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14848:8)
    at Parser.pp$1.parseStatement (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14598:17)
    at Parser.pp$1.parseTopLevel (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14500:21)
    at Parser.parse (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14292:15)
    at Function.parse (C:\Users\mbe\Documents\dev\botassist_docs\node_modules\rollup\dist\shared\rollup.js:14323:35)
error Command failed with exit code 1.
```

```bash
# Paste output of `vuepress info` here
  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 5.01 GB / 15.75 GB
  Binaries:
    Node: 14.17.3 - ~\AppData\Local\Temp\yarn--1627039419154-0.9057674898134078\node.CMD
    Yarn: 1.22.10 - ~\AppData\Local\Temp\yarn--1627039419154-0.9057674898134078\yarn.CMD
    npm: 7.20.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.32.0. - /mingw64/bin/git
  Browsers:
    Chrome: 91.0.4472.164
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.71)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.22
    @vuepress/bundler-webpack:  2.0.0-beta.22
    @vuepress/cli:  2.0.0-beta.22
    @vuepress/client:  2.0.0-beta.21 (2.0.0-alpha.1)
    @vuepress/core:  2.0.0-beta.22 (2.0.0-alpha.1)
    @vuepress/markdown:  2.0.0-beta.22 (2.0.0-alpha.1)
    @vuepress/plugin-active-header-links:  2.0.0-beta.22
    @vuepress/plugin-back-to-top:  2.0.0-beta.22
    @vuepress/plugin-container:  2.0.0-beta.22
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: ^2.0.0-alpha.1 => 2.0.0-alpha.1
    @vuepress/plugin-git:  2.0.0-beta.22
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.22
    @vuepress/plugin-nprogress:  2.0.0-beta.22
    @vuepress/plugin-palette:  2.0.0-beta.22
    @vuepress/plugin-prismjs:  2.0.0-beta.22
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.22
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.21 (2.0.0-alpha.1)
    @vuepress/theme-default:  2.0.0-beta.22
    @vuepress/utils:  2.0.0-beta.21 (2.0.0-alpha.1)
    vue:  3.1.5
    vue-loader:  16.3.3
    vue-router:  4.0.10 (4.0.0-rc.5)
    vuepress: ^2.0.0-beta.22 => 2.0.0-beta.22
    vuepress-vite: ^2.0.0-beta.22 => 2.0.0-beta.22
```

**Comment by Mbensler** [comment]
I removed all plugins which seemed to fix the problem.
