### ISSUE TITLE
[Bug report] markdown plugin markdown-it-katex yarn docs:build fail

### ISSUE THREAD

**Issue by larrykwong** [vuepress/vuepress-next#328]
### Description

install markdown-it-katex and config in config.js like below:  
```
extendsMarkdown: (md) => {
    md.set({html: true})
    md.use(require("markdown-it-katex"))
  }, 
```

version is:
```
"devDependencies": {
    "markdown-it-katex": "^2.0.3",
    "vuepress-vite": "^2.0.0-beta.23"
  }
```

**it WORKS when in yarn docs:dev mode, but FAIL in yarn docs:build**  

> 

the error message is:  
PS E:\Vite\vuepress> yarn docs:build  
yarn run v1.22.10  
$ vuepress build docs  
info Initializing VuePress and preparing data...  
- Compiling with vite  

(!) outDir E:\Vite\vuepress\docs\.vuepress\dist is not inside project root and will not be emptied.
Use --emptyOutDir to override.  

✔ Compiling with vite - done   
- Rendering pages   
- Rendering pages /   
✖ Rendering pages - failed   
TypeError: Invalid value used as weak map key   
    at WeakMap.set (<anonymous>)   
    at normalizePropsOptions (E:\Vite\vuepress\node_modules\_@vue_runtime-core@3.1.5@@vue\runtime-core\dist\runtime-core.cjs.prod.js:2775:15)   
    at createComponentInstance (E:\Vite\vuepress\node_modules\_@vue_runtime-core@3.1.5@@vue\runtime-core\dist\runtime-core.cjs.prod.js:5546:23)       
    at renderComponentVNode (E:\Vite\vuepress\node_modules\_@vue_server-renderer@3.1.5@@vue\server-renderer\dist\server-renderer.cjs.prod.js:181:22)    at Object.ssrRenderComponent    
 (E:\Vite\vuepress\node_modules\_@vue_server-renderer@3.1.5@@vue\server-renderer\dist\server-renderer.cjs.prod.js:517:12)
    at _sfc_ssrRender$i (E:\Vite\vuepress\docs\.vuepress\dist\.server\app.js:1080:24)  
    at renderComponentSubTree (E:\Vite\vuepress\node_modules\_@vue_server-renderer@3.1.5@@vue\server-renderer\dist\server-renderer.cjs.prod.js:247:13)  
    at renderComponentVNode (E:\Vite\vuepress\node_modules\_@vue_server-renderer@3.1.5@@vue\server-renderer\dist\server-renderer.cjs.prod.js:198:16)    at renderVNode (E:\Vite\vuepress\node_modules\_@vue_server-renderer@3.1.5@@vue\server-renderer\dist\server-renderer.cjs.prod.js:288:22)  
    at renderComponentSubTree (E:\Vite\vuepress\node_modules\_@vue_server-renderer@3.1.5@@vue\server-renderer\dist\server-renderer.cjs.prod.js:253:13)  
error Command failed with exit code 1.  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.  
PS E:\Vite\vuepress>   

> 

### Steps to reproduce

- Reproduction link / repo:

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by Mister-Hope** [comment]
This is not a bug at all.

See https://github.com/vuejs/vue-next/issues/3746

**Comment by larrykwong** [comment]
@Mister-Hope Hi man, thanks your reply, but i still can't get it. How to i config the vuepress to make it build successfully?

**Comment by Mister-Hope** [comment]
The issue is including the solution in both my issue and vue team's reply.

**Comment by meteorlxy** [comment]
See https://v2.vuepress.vuejs.org/guide/markdown.html#deprecated-html-tags

MathML tags and deprecated html tags are similar

**Comment by childrentime** [comment]
Just need to configure like this

```ts
import type { ViteBundlerOptions } from '@vuepress/bundler-vite';
import { defineUserConfig } from '@vuepress/cli';
import type { DefaultThemeOptions } from '@vuepress/theme-default';
import markdownItKatex from 'markdown-it-katex';

const customElement = ['mi','mo','mn','mrow','annotation','semantics','math'];
export default defineUserConfig<DefaultThemeOptions, ViteBundlerOptions>({
    
  extendsMarkdown: md => {
    md.use(markdownItKatex);
    md.linkify.set({ fuzzyEmail: false });
  },

  bundlerConfig: {
    vuePluginOptions: {
      template: {
        compilerOptions: {
            isCustomElement: tag => customElement.includes(tag)
        }
      }
    }
  }
});

```
