### ISSUE TITLE
[Bug report] Window 11 can't start dev server

### ISSUE THREAD

**Issue by Assone** [vuepress/vuepress-next#364]
### Description

run dev server error, maybe is deps path error. i see the error is :

```bash
[vite] Internal server error: Failed to resolve import "D:UserDataDesktopProjectNotedocs.vuepressplugins    exclientAppEnhance.ts" from "docs\.vuepress\.temp\internal\clientAppEnhances.js". Does the file exist?
```
then i find this file, I found that some errors were caused by my local plugin.

error log:

```bash
上午9:16:08 [vite] Internal server error: Failed to resolve import "D:UserDataDesktopProjectNotedocs.vuepressplugins    exclientAppEnhance.ts" from "docs\.vuepress\.temp\internal\clientAppEnhances.js". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/UserData/Desktop/Project/Note/docs/.vuepress/.temp/internal/clientAppEnhances.js
  2  |  import clientAppEnhance1 from 'D:/UserData/Desktop/Project/Note/node_modules/@vuepress/plugin-medium-zoom/lib/client/clientAppEnhance.js'
  3  |  import clientAppEnhance2 from 'D:/UserData/Desktop/Project/Note/node_modules/@vuepress/plugin-theme-data/lib/client/clientAppEnhance.js'
     |                                 ^
  5  |  import clientAppEnhance4 from 'D:\UserData\Desktop\Project\Note\docs\.vuepress\plugins\glossary\clientAppEnhance.ts'
  6  |  import clientAppEnhance5 from 'D:\UserData\Desktop\Project\Note\docs\.vuepress\plugins\flowChart\clientAppEnhance.ts'
      at formatError (D:\UserData\Desktop\Project\Note\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:50738:46)
      at TransformContext.error (D:\UserData\Desktop\Project\Note\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:50734:19)
      at normalizeUrl (D:\UserData\Desktop\Project\Note\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:74223:26)
      at async TransformContext.transform (D:\UserData\Desktop\Project\Note\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:74356:57)
      at async Object.transform (D:\UserData\Desktop\Project\Note\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:50939:30)
      at async transformRequest (D:\UserData\Desktop\Project\Note\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:66763:29)
      at async viteTransformMiddleware (D:\UserData\Desktop\Project\Note\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:66904:32)
```

### Steps to reproduce

1. yarn install
2. yarn docs:dev

- Reproduction link / repo: https://github.com/Assone/Note

### Expected behavior

start dev server success.

### Screenshots

![image](https://user-images.githubusercontent.com/14324389/128652294-7039cc35-bf15-4370-b35f-e2f18fd793ac.png)

### Environment info

- Browser: 
<html>
<body>

Microsoft Edge | 92.0.902.67
-- | --

</body>
</html>
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 13.14 GB / 31.91 GB
  Binaries:
    Node: 16.0.0 - C:\Users\ADMINI~1\AppData\Local\Temp\yarn--1628472471969-0.16980447796695697\node.CMD
    Yarn: 1.22.10 - C:\Users\ADMINI~1\AppData\Local\Temp\yarn--1628472471969-0.16980447796695697\yarn.CMD
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.32.0. - /cmd/git
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (92.0.902.67)
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.23
    @vuepress/bundler-webpack:  2.0.0-beta.23
    @vuepress/cli:  2.0.0-beta.23
    @vuepress/client:  2.0.0-beta.23
    @vuepress/core:  2.0.0-beta.23
    @vuepress/markdown:  2.0.0-beta.23
    @vuepress/plugin-active-header-links:  2.0.0-beta.23
    @vuepress/plugin-back-to-top:  2.0.0-beta.23
    @vuepress/plugin-container:  2.0.0-beta.23
    @vuepress/plugin-debug: ^2.0.0-beta.23 => 2.0.0-beta.23
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.23
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.23
    @vuepress/plugin-nprogress:  2.0.0-beta.23
    @vuepress/plugin-palette:  2.0.0-beta.23
    @vuepress/plugin-prismjs:  2.0.0-beta.23
    @vuepress/plugin-pwa: ^2.0.0-beta.23 => 2.0.0-beta.23
    @vuepress/plugin-pwa-popup: ^2.0.0-beta.23 => 2.0.0-beta.23
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: ^2.0.0-beta.23 => 2.0.0-beta.23
    @vuepress/plugin-theme-data:  2.0.0-beta.23
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.23
    @vuepress/theme-default:  2.0.0-beta.23
    @vuepress/utils:  2.0.0-beta.23
    vue:  3.1.5
    vue-loader:  16.5.0
    vue-router:  4.0.10
    vuepress: ^2.0.0-beta.23 => 2.0.0-beta.23
    vuepress-vite: ^2.0.0-beta.23 => 2.0.0-beta.23
```

**Comment by meteorlxy** [comment]
Seems that it's caused by your local plugins.

Remember to use `const { path } = require('@vuepress/utils')` instead of `const path = require('path')`
