### ISSUE TITLE
Custom directive is missing corresponding SSR transform and will be ignored

### ISSUE THREAD

**Issue by bhabgs** [vuepress/vuepress-next#373]
## Bug report
Custom directive is missing corresponding SSR transform and will be ignored
### Description
自定义指令在开发阶段不会产生错误，yarn docs:build, 时会提示如下信息
`Custom directive is missing corresponding SSR transform and will be ignored`

### Steps to reproduce

在vuepress next 下添加自定义指令错误，
[demo](https://github.com/bhabgs/vite-vui-docs)

- Reproduction link / repo:

### Screenshots

runing >
![image](https://user-images.githubusercontent.com/19221378/128958533-717d0562-ac59-4f73-b5e1-8c893baa77ee.png)

building >
![image](https://user-images.githubusercontent.com/19221378/128958514-0561b3cc-67d9-4075-a2c0-87cfb63a2178.png)

### Environment info

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 134.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.1

```bash
  stack: 'ModuleError: Module Error (from ./node_modules/vue-loader/dist/templateLoader.js):\n' +
    '\n' +
    '\x1B[31mVueCompilerError: Custom directive is missing corresponding SSR transform and will be ignored.\x1B[39m\n' +
    '\x1B[90mat /Users/bhabgs/github/vite-vui-docs/docs/.vuepress/components/contentmenu.vue:4:5\x1B[39m\n' +
    '\x1B[33m2  |    <div\x1B[39m\n' +
    '\x1B[33m3  |      class="contextmenu_box"\x1B[39m\n' +
    `\x1B[33m4  |      v-contextmenu="{ menus: [{ key: '1', name: '哈哈' }], callBack() {} }"\x1B[39m\n` +
    '\x1B[33m   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\x1B[39m\n' +
    '\x1B[33m5  |    >\x1B[39m\n' +
    '\x1B[33m6  |      contextmenu_box 自定义右键菜单\x1B[39m\n' +
    '\n' +
    '    at Object.emitError (/Users/bhabgs/github/vite-vui-docs/node_modules/webpack/lib/NormalModule.js:562:6)\n' +
    '    at /Users/bhabgs/github/vite-vui-docs/node_modules/vue-loader/dist/templateLoader.js:62:31\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Object.TemplateLoader (/Users/bhabgs/github/vite-vui-docs/node_modules/vue-loader/dist/templateLoader.js:56:25)\n' +
    '    at LOADER_EXECUTION (/Users/bhabgs/github/vite-vui-docs/node_modules/loader-runner/lib/LoaderRunner.js:132:14)\n' +
    '    at runSyncOrAsync (/Users/bhabgs/github/vite-vui-docs/node_modules/loader-runner/lib/LoaderRunner.js:133:4)\n' +
    '    at iterateNormalLoaders (/Users/bhabgs/github/vite-vui-docs/node_modules/loader-runner/lib/LoaderRunner.js:250:2)\n' +
    '    at iterateNormalLoaders (/Users/bhabgs/github/vite-vui-docs/node_modules/loader-runner/lib/LoaderRunner.js:239:10)\n' +
    '    at /Users/bhabgs/github/vite-vui-docs/node_modules/loader-runner/lib/LoaderRunner.js:254:3\n' +
    '    at runSyncOrAsync (/Users/bhabgs/github/vite-vui-docs/node_modules/loader-runner/lib/LoaderRunner.js:143:11)',
  compilerPath: undefined
}
✖ Compiling with webpack - failed
Error: Failed to compile with errors
    at /Users/bhabgs/github/vite-vui-docs/node_modules/@vuepress/bundler-webpack/lib/build/createBuild.js:37:28
    at /Users/bhabgs/github/vite-vui-docs/node_modules/webpack/lib/webpack.js:141:8
    at /Users/bhabgs/github/vite-vui-docs/node_modules/neo-async/async.js:2830:7
    at done (/Users/bhabgs/github/vite-vui-docs/node_modules/neo-async/async.js:2865:11)
    at /Users/bhabgs/github/vite-vui-docs/node_modules/neo-async/async.js:2818:7
    at /Users/bhabgs/github/vite-vui-docs/node_modules/webpack/lib/HookWebpackError.js:68:3
    at _done (eval at create (/Users/bhabgs/github/vite-vui-docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/bhabgs/github/vite-vui-docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
error Command failed with exit code 1.
```

**Comment by meteorlxy** [comment]
You need to set `directiveTransforms` options to make custom directive work in SSR, or just wrap it with `<ClientOnly>`

**Comment by bhabgs** [comment]
> You need to set `directiveTransforms` options to make custom directive work in SSR, or just wrap it with `<ClientOnly>`

这好像并没有解决我的问题，我在查看vitepress的时候看到过这个选项。

**Comment by trickyEdecay** [comment]
i solve my directive problem through:

wrap `<ClientOnly>` to the element using directive and set `directiveTransforms` in `config.js` like
```html
<div v-contextmenu></div>
```
```js
{
  directiveTransforms: {
      // v-contextmenu -> contextmenu
      contextmenu: () => ({
        props: [],
        needRuntime: true // <- remember this
      })
  }
}
```
