### ISSUE TITLE
[Bug report] TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by 1chiSensei** [vuepress/vuepress-next#420]
### Description

```bash
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2215:15)
    at createComponentInstance (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5046:23)
    at renderComponentVNode (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:180:22)
    at Object.ssrRenderComponent (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:606:12)
    at _sfc_ssrRender$3 (/home/tomiocodes/AuxBot-Docs/.vuepress/dist/.server/app.js:1226:24)
    at renderComponentSubTree (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:246:13)
    at renderComponentVNode (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:197:16)
    at renderVNode (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:287:22)
    at renderComponentSubTree (/home/tomiocodes/AuxBot-Docs/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:252:13)
```

### Steps to reproduce

Run `yarn vuepress build`

- Reproduction link / repo: https://github.com/1chiSensei/AuxBot-Docs/tree/refactor/move-to-vuepress

### Expected behavior

Successful build.

### Environment info

- Browser: Brave
- Output of `vuepress info`:

```bash
  System:
    OS: Linux 4.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
    Memory: 632.63 MB / 3.89 GB
    Shell: 3.3.0 - /usr/bin/fish
  Binaries:
    Node: 16.4.0 - /tmp/xfs-5793de30/node
    Yarn: 3.1.0-rc.1 - /tmp/xfs-5793de30/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Utilities:
    Git: 2.20.1 - /usr/bin/git
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.25 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.25 
    @vuepress/client:  2.0.0-beta.25 
    @vuepress/core:  2.0.0-beta.25 
    @vuepress/markdown:  2.0.0-beta.25 
    @vuepress/plugin-active-header-links:  2.0.0-beta.25 
    @vuepress/plugin-back-to-top:  2.0.0-beta.25 
    @vuepress/plugin-container:  2.0.0-beta.25 
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git:  2.0.0-beta.25 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.25 
    @vuepress/plugin-nprogress:  2.0.0-beta.25 
    @vuepress/plugin-palette:  2.0.0-beta.25 
    @vuepress/plugin-prismjs:  2.0.0-beta.25 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: next => 2.0.0-beta.25 
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.25 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.25 
    @vuepress/theme-default:  2.0.0-beta.25 
    @vuepress/utils:  2.0.0-beta.25 
    vue:  3.2.6 
    vue-loader: Not Found
    vue-router:  4.0.11 
    vuepress: Not Found
    vuepress-vite: next => 2.0.0-beta.25
```

**Comment by meteorlxy** [comment]
I could not find the source code of `@discord-message-components/vue` that you are using.

I think the reason could be that it's not ready for SSR. You could try to wrap the component with `ClientOnly`.

See https://v2.vuepress.vuejs.org/reference/components.html#clientonly
