### ISSUE TITLE
[Bug report] - Unable to link libs/ in an example environment docs/

### ISSUE THREAD

**Issue by GregoireF** [vuepress/vuepress-next#510]
### Description
Hi all, I am trying to eject the default theme present in [the default theme](https://github.com/vuepress/vuepress-next/tree/main/packages/%40vuepress/theme-default) by putting it in my `lib/` folder at the root.
After that, in order to set up an example environment through the `docs/` folder in the root. I try to access the default theme configuration and try to get it out:

```js
export default({
    ...
    theme: path.resolve(__dirname, '../../lib/'),
    ...
)}
```

### Steps to reproduce
- Eject [the default theme](https://github.com/vuepress/vuepress-next/tree/main/packages/%40vuepress/theme-default) by putting it in my `lib/` folder at the root.
- Create a `docs/` folder in the root
- Add a config.ts file in docs/.vuepress/
- Submit the following configuration :
```js
export default({
    ...
    theme: path.resolve(__dirname, '../../lib/'),
    ...
)}
```
### Expected behavior

Normally, if I am not mistaken, with VuePress1.X I do not encounter this type of incident. Is there a solution to work around it?

### Incident

```bash
yarn dev:docs
yarn run v1.22.11
$ vuepress dev docs --clean-cache
ReferenceError: __VUEPRESS_DEV__ is not defined
    at Object.<anonymous> (F:\xampp\htdocs\projects\vuepress-theme-webready\lib\composables\useDarkMode.ts:33:31)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.require.extensions..ts (F:\xampp\htdocs\projects\vuepress-theme-webready\node_modules\vuepress\node_modules\@vuepress\cli\lib\utils\allowTs.js:11:11)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (F:\xampp\htdocs\projects\vuepress-theme-webready\lib\composables\index.ts:20:32)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.require.extensions..ts (F:\xampp\htdocs\projects\vuepress-theme-webready\node_modules\vuepress\node_modules\@vuepress\cli\lib\utils\allowTs.js:11:11)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (F:\xampp\htdocs\projects\vuepress-theme-webready\lib\index.ts:20:32)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
error Command failed with exit code 1.
```

### Environment info

- Browser: Google
- Output of `vuepress info`:

```bash
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 1.44 GB / 7.96 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.32.0. - C:\Program Files\Git\cmd\git.EXE
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: Not Found
    @vuepress/client: Not Found
    @vuepress/core: Not Found
    @vuepress/markdown: Not Found
    @vuepress/plugin-active-header-links: Not Found
    @vuepress/plugin-back-to-top: Not Found
    @vuepress/plugin-container: Not Found
    @vuepress/plugin-debug: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-git: Not Found
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: Not Found
    @vuepress/plugin-nprogress: Not Found
    @vuepress/plugin-palette: Not Found
    @vuepress/plugin-prismjs: Not Found
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data: Not Found
    @vuepress/plugin-toc: Not Found
    @vuepress/shared: Not Found
    @vuepress/theme-default: Not Found
    @vuepress/utils: Not Found
    vue: Not Found
    vue-loader: Not Found
    vue-router: Not Found
    vuepress: Not Found
    vuepress-vite: Not Found
```

**Comment by Mister-Hope** [comment]
Please try to give to correct output to list your VuePress packages, and please give us a minimal reproduction (I think this is not hard in your case, you should be able to provide one within 5 minutes.)

**Comment by GregoireF** [comment]
Hi @Mister-Hope,
 
Thanks for your quick feedback.
You can find a test repo [here](https://github.com/GregoireF/vuepress-test). I just tried again on my side, I don't get the error `__VUEPRESS_DEV__ is not defined` anymore.
However, when I run `vuepress info` I always have the above output already provided.
However, you can see in `lib/client/styles/vars-dark.scss` the changes are not reflected in the `docs/` environment.

**Comment by Mister-Hope** [comment]
I think you should point to `lib/node` instead of `lib/client`

**Comment by GregoireF** [comment]
@Mister-Hope, thanks for your quick feedback.
I just tried your method, here is what VuePress returns to me now:

```bash
yarn dev:docs
yarn run v1.22.11
warning package.json: No license field
$ vuepress dev docs --clean-cache
info Cleaning cache...
info Initializing VuePress and preparing data...
error client file does not exist: F:/xampp/htdocs/projects/vuepress/lib/client/clientAppEnhance.js
error error in hook clientAppEnhanceFiles from @vuepress/theme-default
Error: client file does not exist: F:/xampp/htdocs/projects/vuepress/lib/client/clientAppEnhance.js
    at Object.createError (F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\utils\lib\logger.js:27:12)
    at Object.hook (F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\core\lib\pluginApi\normalizeClientFilesHook.js:23:34)
    at async Object.process (F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\core\lib\pluginApi\createHookQueue.js:26:37)
    at async prepareClientAppEnhances (F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\core\lib\app\prepare\prepareClientAppEnhances.js:9:35)
    at async appPrepare (F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\core\lib\app\appPrepare.js:34:5)
    at async dev (F:\xampp\htdocs\projects\vuepress\node_modules\vuepress\node_modules\@vuepress\cli\lib\commands\dev\createDev.js:49:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by GregoireF** [comment]
Hello to all,
On my side, I discovered in `node/defaultTheme.ts` there are two incidents in my opinion:
```js
clientAppEnhanceFiles: path.resolve(
      __dirname,
      '../client/clientAppEnhance.js'
    ),

    clientAppSetupFiles: path.resolve(__dirname, '../client/clientAppSetup.js'),
```

The files are however in .ts. Once renamed, a new error occurs:
```bash
yarn dev:docs
yarn run v1.22.11
warning package.json: No license field
$ vuepress dev docs --clean-cache
info Cleaning cache...
info Initializing VuePress and preparing data...
√ Compilation finished in 3419ms
success VuePress webpack dev server is listening at http://localhost:8081/
ERROR in ./docs/.vuepress/.temp/internal/clientAppEnhances.js 4:35
Module parse failed: Bad character escape sequence (4:35)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import clientAppEnhance1 from 'F:/xampp/htdocs/projects/vuepress/node_modules/@vuepress/plugin-medium-zoom/lib/client/clientAppEnhance.js'
| import clientAppEnhance2 from 'F:/xampp/htdocs/projects/vuepress/node_modules/@vuepress/plugin-theme-data/lib/client/clientAppEnhance.js'
> import clientAppEnhance3 from 'F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\plugin-docsearch\lib\clientAppEnhance.js'
|
| export const clientAppEnhances = [

ERROR in ./docs/.vuepress/.temp/internal/clientAppRootComponents.js 2:41
Module parse failed: Bad character escape sequence (2:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import clientAppRootComponent0 from 'F:/xampp/htdocs/projects/vuepress/node_modules/@vuepress/plugin-back-to-top/lib/client/components/BackToTop.js'
> import clientAppRootComponent1 from 'F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\plugin-debug\lib\components\Debug.js'
|
| export const clientAppRootComponents = [

webpack compiled with 2 errors
```

The .temp folder has been deleted, but the same error still occurs.

**Comment by Mister-Hope** [comment]
Hi, you should try to copy the compiled file, because that's what official repo are doing.(And that's why clientEhanceApp file entrance option has a `.js` extension.

So I suggest you just copy the compiled file in `node_modules` directly and have a try, if it works, then everything should be alright.

I understand you may prefer to use source file for maintenance resons, but in that case you should try to find out all the editions you should make by yourself.

**Comment by Mister-Hope** [comment]
Also, for the error you provide later, make sure you are using `upath` module from `@vuepress/utils`, since the path sperator is different on windows, the native `path` module which Node.js provides won't work.

**Comment by Mister-Hope** [comment]
Also, please remove this

https://github.com/GregoireF/vuepress-test/blob/main/package.json#L58-L58

Mixing v1 v2 deps may lead to werid results.

**Comment by GregoireF** [comment]
Hi @Mister-Hope, I tried your directions.

- Removing `@vuepress/plugin-register-components 1.X` and putting `@vuepress/plugin-register-components 2.X` in place
- Adding `@vuepress/bundler-webpack 2.X`
- Use of `@vuepress/utils` to provide `upath` instead of `path`.

However, here are the incidents I am encountering at the moment :

When launching the local development server:
```bash
yarn dev:docs
yarn run v1.22.11
warning package.json: No license field
$ vuepress dev docs --clean-cache
info Cleaning cache...
info Initializing VuePress and preparing data...
√ Compilation finished in 3249ms
success VuePress webpack dev server is listening at http://localhost:8081/
WARNING in ./docs/.vuepress/.temp/internal/clientAppSetups.js 6:2-17
export 'default' (imported as 'clientAppSetup0') was not found in 'F:/xampp/htdocs/projects/vuepress/docs/.vuepress/.temp/internal/clientAppSetups.js' (possible exports: clientAppSetups)

ERROR in ./docs/.vuepress/.temp/internal/clientAppEnhances.js 4:35
Module parse failed: Bad character escape sequence (4:35)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import clientAppEnhance1 from 'F:/xampp/htdocs/projects/vuepress/node_modules/@vuepress/plugin-medium-zoom/lib/client/clientAppEnhance.js'
| import clientAppEnhance2 from 'F:/xampp/htdocs/projects/vuepress/node_modules/@vuepress/plugin-theme-data/lib/client/clientAppEnhance.js'
> import clientAppEnhance3 from 'F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\plugin-docsearch\lib\clientAppEnhance.js'
| import clientAppEnhance4 from 'F:/xampp/htdocs/projects/vuepress/docs/.vuepress/.temp/register-components/clientAppEnhance.4df4004c.js'
|

ERROR in ./docs/.vuepress/.temp/internal/clientAppRootComponents.js 2:41
Module parse failed: Bad character escape sequence (2:41)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import clientAppRootComponent0 from 'F:/xampp/htdocs/projects/vuepress/node_modules/@vuepress/plugin-back-to-top/lib/client/components/BackToTop.js'
> import clientAppRootComponent1 from 'F:\xampp\htdocs\projects\vuepress\node_modules\@vuepress\plugin-debug\lib\components\Debug.js'
|
| export const clientAppRootComponents = [

webpack compiled with 2 errors and 1 warning
```

The error encountered with the use of `upath` : 
```bash
TypeError: Cannot read property 'resolve' of undefined
    at Object.<anonymous> (F:\xampp\htdocs\projects\vuepress\docs\.vuepress\config.ts:86:29)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.require.extensions..ts (F:\xampp\htdocs\projects\vuepress\node_modules\vuepress\node_modules\@vuepress\cli\lib\utils\allowTs.js:11:11)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadUserConfigEs (F:\xampp\htdocs\projects\vuepress\node_modules\vuepress\node_modules\@vuepress\cli\lib\config\loadUserConfigEs.js:9:22)
    at loadUserConfig (F:\xampp\htdocs\projects\vuepress\node_modules\vuepress\node_modules\@vuepress\cli\lib\config\loadUserConfig.js:16:20)
    at resolveDevUserConfig (F:\xampp\htdocs\projects\vuepress\node_modules\vuepress\node_modules\@vuepress\cli\lib\commands\dev\resolveDevUserConfig.js:43:58)
```

Moreover, I tried to target directly the files in `docs/.vuepress/.temp/internal` by configuring the `lib/node/defaultTheme.ts` file: 
```js
clientAppEnhanceFiles: path.resolve(
      __dirname,
      '../../docs/.vuepress/.temp/internal/clientAppEnhances.js'
    ),

    clientAppSetupFiles: path.resolve(__dirname, '../../docs/.vuepress/.temp/internal/clientAppSetups.js'),
```
With this configuration, I still have the same error as above.

**Comment by GregoireF** [comment]
Hello to all,

I take the liberty of re-launching this ongoing incident.
- Should we consider it as an unresolvable incident and follow the cookbook for writing a plugin and provide a demo link once the package is released?
- Another approach can be used?
- A lack of configuration on my side?

**Comment by GregoireF** [comment]
Hello @meteorlxy @Mister-Hope , 

Having worked on this issue, I can say that it is now resolved. I will share with you in the next 48 hours a test environment for the purpose of developing a theme for the community to potentially serve as a launch pad. 
Once this last task is done, I will close this incident.

Thanks for your help and collaboration.
