### ISSUE TITLE
[Bug report] 当使用typora修改md文件时，运行的开发服务器停止运行

### ISSUE THREAD

**Issue by FreedomFoolt** [vuepress/vuepress-next#546]
### Description

在WebStorm中运行`vuepress dev docs`后，在WebStorm中修改markdown文件没有问题。但是通过Typora修改markdown文件时，会出现错误，停止开发服务器的运行。不使用WebStorm，win10系统中用cmd运行开发服务器时，也会出现此问题。

### Steps to reproduce

- Reproduction link / repo:

### Environment info
- vuepress: @2.0.0-beta.27
- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here

error error in hook extendsPageData from @vuepress/plugin-git
E:\Vue\vue-press\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 128: git --no-pager log -1 --format=%at it/Front-end-Web/09. Vue/.~15. Vue press.md
fatal: ambiguous argument 'it/Front-end-Web/09. Vue/.~15. Vue press.md': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
    at makeError (E:\Vue\vue-press\node_modules\execa\lib\error.js:60:11)
    at handlePromise (E:\Vue\vue-press\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getUpdatedTime (E:\Vue\vue-press\node_modules\@vuepress\plugin-git\lib\node\utils\getUpdatedTime.js:9:24)
    at async Object.extendsPageData [as hook] (E:\Vue\vue-press\node_modules\@vuepress\plugin-git\lib\node\gitPlugin.js:19:35)
    at async Object.process (E:\Vue\vue-press\node_modules\@vuepress\core\lib\pluginApi\createHookQueue.js:26:37)
    at async resolvePageData (E:\Vue\vue-press\node_modules\@vuepress\core\lib\page\resolvePageData.js:19:29)
    at async createPage (E:\Vue\vue-press\node_modules\@vuepress\core\lib\page\createPage.js:120:17)
    at async handlePageAdd (E:\Vue\vue-press\node_modules\@vuepress\cli\lib\commands\dev\handlePageAdd.js:15:23) {
  shortMessage: 'Command failed with exit code 128: git --no-pager log -1 --format=%at it/Front-end-Web/09. Vue/.~15. Vue press.md',
  command: 'git --no-pager log -1 --format=%at it/Front-end-Web/09. Vue/.~15. Vue press.md',
  escapedCommand: 'git --no-pager log -1 "--format=%at" "it/Front-end-Web/09. Vue/.~15. Vue press.md"',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: ambiguous argument 'it/Front-end-Web/09. Vue/.~15. Vue press.md': unknown revision or path not in the working tree.\n" +
    "Use '--' to separate paths from revisions, like this:\n" +
    "'git <command> [<revision>...] -- [<file>...]'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by meteorlxy** [comment]
看错误日志有这样一个文件 `09. Vue/.~15. Vue press.md` 是不是 Typora 会在当前目录下生成类似 `.~` 开头的临时文件？你可以通过 [pagePatterns](https://vuepress.github.io/reference/config.html#pagepatterns) 配置来忽略这些临时文件

**Comment by FreedomFoolt** [comment]
确实是此问题，设置`pagePatterns: ['**/[^.~]*.md', '!.vuepress', '!node_modules']`，已解决。
