### ISSUE TITLE
[Feature request] Support esm plugin

### ISSUE THREAD

**Issue by Mister-Hope** [vuepress/vuepress-next#617]
### Description

```
$ vuepress-webpack dev __tests__/demo
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\projects\vuepress-theme-hope\packages\add-this\lib\node\index.js from C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\resolvePluginModule.js not supported.
Instead change the require of index.js in C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\resolvePluginModule.js to a dynamic import() which is available in all CommonJS modules.
    at resolvePluginModule (C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\resolvePluginModule.js:16:26)
    at resolvePluginObject (C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\resolvePluginObject.js:12:57)
    at C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\resolvePluginsFromConfig.js:12:65
    at Array.reduce (<anonymous>)
    at resolvePluginsFromConfig (C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\resolvePluginsFromConfig.js:9:65)
    at createBaseApp (C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\createBaseApp.js:45:77)
    at createDevApp (C:\projects\vuepress-theme-hope\node_modules\@vuepress\core\lib\app\createDevApp.js:10:51)
    at dev (C:\projects\vuepress-theme-hope\node_modules\@vuepress\cli\lib\commands\dev\createDev.js:27:45)
```

It would be much more easy for developers if vuepress support loading esm plugins

Now I must comile node side to cjs while compile client side to esm, and if they are sharing some files, it would be difficult for developers to handle the shared files.

So if native esm is supported, the whole plugin or theme can write in esm and provide esm while declaring `"type": "module"`.

(BTW, **more and more packages are moving to esm. so if vuepress doesn't support it, plugin and themes cannot require those packages directly on node side**, instead they must bundle the deps using bundler like rollup, so deps can not be automaticlly updated on user side)

### Proposed Solution

Compile `@vuepress/core` and `@vuepress/bundler-xxx` to esm, and support loading esm plugins and themes.

**Comment by DerYeger** [comment]
This is a huge issue for me because it's not just relevant for plugins.

I'd love to include an interactive demo in my docs,
`vuepress dev` works fine and as expected.
However, `vuepress build` fails with the following error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\janmu\workspace\d3-graph-controller\node_modules\d3-selection\src\index.js from C:\Users\janmu\workspace\d3-graph-controller\docs\.vuepress\dist\.server\app.js not supported.
Instead change the require of index.js in C:\Users\janmu\workspace\d3-graph-controller\docs\.vuepress\dist\.server\app.js to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (C:\Users\janmu\workspace\d3-graph-controller\docs\.vuepress\dist\.server\app.js:29:19)
    at C:\Users\janmu\workspace\d3-graph-controller\node_modules\@vuepress\bundler-vite\lib\build\createBuild.js:39:34
    at async C:\Users\janmu\workspace\d3-graph-controller\node_modules\@vuepress\utils\lib\withSpinner.js:12:24
    at async Object.build (C:\Users\janmu\workspace\d3-graph-controller\node_modules\@vuepress\bundler-vite\lib\build\createBuild.js:30:5)
    at async C:\Users\janmu\workspace\d3-graph-controller\node_modules\@vuepress\cli\lib\commands\build\createBuild.js:49:5
error Command failed with exit code 1.                       
```

**Comment by AnWeber** [comment]
Vue CLI solves this feature with this code: https://github.com/vuejs/vue-cli/blob/dd217b2309934a39130990094feee9acd9ff3869/packages/%40vue/cli-service/lib/util/loadFileConfig.js
