### ISSUE TITLE
[Bug report]TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by juukee** [vuepress/vuepress-next#677]
```
✔ Compiling with vite - done
✖ Rendering pages - failed
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2737:15)
    at createComponentInstance (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5598:23)
    at renderComponentVNode (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:194:22)
    at Object.ssrRenderComponent (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:626:12)
    at _sfc_ssrRender$1X (/home/ubuntu/RemoteWorking/vast/docs/.vuepress/dist/.server/app.js:2018:24)
    at renderComponentSubTree (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:266:13)
    at renderComponentVNode (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:211:16)
    at renderVNode (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:307:22)
    at renderComponentSubTree (/home/ubuntu/RemoteWorking/vast/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:272:13)
```

**Comment by Mister-Hope** [comment]
This simple helps nothing.

There must be something wrong with your markdown. theme or plugin files, and let Vue fails when SSR rendering

**Comment by juukee** [comment]
> This simple helps nothing.
> 
> There must be something wrong with your markdown. theme or plugin files, and let Vue fails when SSR rendering

because I don't know how it happened,it look like some md files error, but can't know which one

**Comment by lixpAAA** [comment]
亲身经历，打包出现这个错误， 最后发现 确实是有的 .md 文件内容有问题

**Comment by olets** [comment]
- Search engines led me here but the issue I needed to find was #766. Sharing in case it happens to others
