### ISSUE TITLE
[Bug report] Running "npm run docs:dev" fails when using local theme

### ISSUE THREAD

**Issue by cezarmaftei** [vuepress/vuepress-next#697]
I created a basic Vuepress 2 website, using the code from the guide: https://v2.vuepress.vuejs.org/guide/getting-started.html. Everything works fine when using the default theme.

The issue occurred when I created a local theme. Running the dev command `npm run docs:dev` works fine, but when I run the build command `npm run docs:build` it fails, throwing the following message:
```
Rendering pages - failed
TypeError: Cannot read properties of undefined (reading 'fileName')
    at renderPageStyles (D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\renderPageStyles.js:7:122)
    at renderPage (D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\renderPage.js:43:88)
    at async D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\createBuild.js:46:13
    at async D:\vuepress\vuepress-docs\node_modules\@vuepress\utils\lib\withSpinner.js:12:24
    at async Object.build (D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\createBuild.js:30:5)
    at async D:\vuepress\vuepress-docs\node_modules\@vuepress\cli\lib\commands\build\createBuild.js:49:5
```
Repo [here](https://github.com/cezarmaftei/vuepress-local-theme).

**Comment by ste-brennan-maersk** [comment]
Yep I get the same on Macbook Pro M1:

`✖ Rendering pages - failed
TypeError: Cannot read property 'fileName' of undefined
    at renderPageStyles (/Users/username/vp-next-test/node_modules/@vuepress/bundler-vite/lib/build/renderPageStyles.js:7:122)
    at renderPage (/Users/username/vp-next-test/node_modules/@vuepress/bundler-vite/lib/build/renderPage.js:43:88)
    at async /Users/username/vp-next-test/node_modules/@vuepress/bundler-vite/lib/build/createBuild.js:46:13
    at async /Users/username/vp-next-test/node_modules/@vuepress/utils/lib/withSpinner.js:12:24
    at async Object.build (/Users/username/vp-next-test/node_modules/@vuepress/bundler-vite/lib/build/createBuild.js:30:5)
    at async /Users/username/vp-next-test/node_modules/vuepress/node_modules/vuepress-vite/node_modules/@vuepress/cli/lib/commands/build/createBuild.js:49:5`
