### ISSUE TITLE
[Bug report] Adding external library option to configure webpack results in warning and error. 

### ISSUE THREAD

**Issue by aceofwings** [vuepress/vuepress-next#724]
### Description

Project requires client side dependency, needed to be externally included. In vuepress's config, we explicitly set bundler to vuepress/bundler-webpack and set bootstrap as an external library. 

Example being

```
    configureWebpack: (config, isServer, isBuild) => {
      if (isBuild) {
        return {externals: {boostrap: 'bootstrap'}}
      }
    },
```

Repo with described changes [here](https://github.com/cdmoro/bootstrap-vue-3/tree/fix/docs)
### Steps to reproduce

We build project 
`npm run build`

then we run the following command in project directory 

`npm exec --workspace=docs vuepress build . `

### Additional Behavior Notes
By setting no external, no issues are present and the compilation states as being successfully. By defining any external lib of any sort the error below is shown but the compilation still succeeds. 
### Screenshots

```
[Vue warn]: Component VuepressApp  is missing template or render function.
⠹ Rendering pages /components/Overlay.htmlError: usePageHead() is called without provider.
    at usePageHead (C:\Users\DanielH\Documents\bootstrap-vue-3\docs\.vuepress\dist\.server\app.js:17927:15)
    at setupUpdateHead (C:\Users\DanielH\Documents\bootstrap-vue-3\docs\.vuepress\dist\.server\app.js:17461:57)
    at setup (C:\Users\DanielH\Documents\bootstrap-vue-3\docs\.vuepress\dist\.server\app.js:17577:13)
    at callWithErrorHandling (C:\Users\DanielH\Documents\bootstrap-vue-3\docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:119:22)
    at setupStatefulComponent (C:\Users\DanielH\Documents\bootstrap-vue-3\docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5704:29)
    at setupComponent (C:\Users\DanielH\Documents\bootstrap-vue-3\docs\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5685:11)
    at renderComponentVNode (C:\Users\DanielH\Documents\bootstrap-vue-3\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:195:17)
    at C:\Users\DanielH\Documents\bootstrap-vue-3\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:459:30
    at Generator.next (<anonymous>)

```

### Environment info
No Browser

```bash
# 2.0.0-beta.35
```

**Comment by xxiaojiujiu** [comment]
so how did you resolve this problem?

**Comment by aceofwings** [comment]
I can reopen the issue. The problem was not solved. It was really weird behavior.

**Comment by patchshorts** [comment]
Seems related to #103

**Comment by yuanbug** [comment]
still meet this issue using  beta41
