### ISSUE TITLE
[Bug report] Cannot use Vue SFC in new project

### ISSUE THREAD

**Issue by ottopaulsen** [vuepress/vuepress-next#741]
### Description

I am creating a new Vuepress 2 project following the [manual installation guide](https://v2.vuepress.vuejs.org/guide/getting-started.html#manual-installation).

The I am adding a simple (Hello World) Vue SFC component, with what I believe is the necessary config.
I add the component to the README.md
When I run the server and opens the file, I get an error:

```
[plugin:vite:vue] Illegal tag name. Use '&lt;' to print '<'.
[/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vuepress/theme-default/lib/client/layouts/Layout.vue:40:29]()
34 |    touchStart.y = e.changedTouches[0].clientY
35 |  }
36 |  const onTouchEnd = (e): void => {
   |                                  ^
37 |    const dx = e.changedTouches[0].clientX - touchStart.x
38 |    const dy = e.changedTouches[0].clientY - touchStart.y
    at createCompilerError ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:19:19]())
    at emitError ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:1594:29]())
    at parseChildren ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:953:21]())
    at Object.baseParse ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:852:23]())
    at Object.parse ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3077:25]())
    at Object.parse ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:4780:26]())
    at createDescriptor ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vitejs/plugin-vue/dist/index.js:4139:43]())
    at transformMain ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vitejs/plugin-vue/dist/index.js:4487:34]())
    at TransformContext.transform ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/@vitejs/plugin-vue/dist/index.js:4853:16]())
    at Object.transform ([/Users/otto/dev/red-nodes/temp/vuepress-starter/node_modules/vite/dist/node/chunks/dep-9]()
```

### Steps to reproduce

```
npm init
npm install -D vuepress@next
echo 'node_modules' >> .gitignore
echo '.temp' >> .gitignore
echo '.cache' >> .gitignore
mkdir docs
echo '# Hello VuePress' > docs/README.md
npm run docs:dev
```

Add file `docs/.vuepress/components/MyComponent.vue`:

```vue
<template>
  <p>This is a test component</p>
</template>
```

Add file `docs/.vuepress/config.js`:

```js
// import vue from "@vitejs/plugin-vue";

const { path } = require("@vuepress/utils");
const vue = require("@vitejs/plugin-vue");

module.exports = {
  lang: "en-US",
  title: "Test",
  description: "A test",
  base: "/",
  plugins: [
    [
      "@vuepress/register-components",
      {
        componentsDir: path.resolve(__dirname, "./components"),
      },
    ],
  ],
  bundlerConfig: {
    viteOptions: {
      plugins: [vue()],
    },
  },
};
```

And here is my `package.json`:
```json
{
  "name": "vuepress-starter",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "docs:dev": "vuepress dev docs",
    "docs:build": "vuepress build docs"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "vuepress": "^2.0.0-beta.36",
    "@vuepress/plugin-register-components": "^2.0.0-beta.36"
  }
}
```

And `docs/README.md`:
```md
# Hello VuePress

Here it is:

<MyComponent/>

```

Then run
```
npm install
npm run docs:dev
```

and open the docs.

- Reproduction link / repo: https://github.com/ottopaulsen/vuepress-failing

### Expected behavior

I expect the documentation to open without error and show the text in the component template.

### Screenshots

![Screenshot](https://raw.githubusercontent.com/ottopaulsen/vuepress-failing/main/failing-vuepress.png)

### Environment info

- Browser: Chrome
- Output of `vuepress info`:

```bash
 System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Memory: 94.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: Not Found
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Utilities:
    Git: 2.24.3 - /usr/bin/git
  Browsers:
    Chrome: 99.0.4844.51
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.2
  npmPackages:
    @vuepress/bundler-vite:  2.0.0-beta.36 
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.36 
    @vuepress/client:  2.0.0-beta.35 
    @vuepress/core:  2.0.0-beta.36 
    @vuepress/markdown:  2.0.0-beta.36 
    @vuepress/plugin-active-header-links:  2.0.0-beta.36 
    @vuepress/plugin-back-to-top:  2.0.0-beta.36 
    @vuepress/plugin-container:  2.0.0-beta.36 
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.36 
    @vuepress/plugin-git:  2.0.0-beta.36 
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.36 
    @vuepress/plugin-nprogress:  2.0.0-beta.36 
    @vuepress/plugin-palette:  2.0.0-beta.36 
    @vuepress/plugin-prismjs:  2.0.0-beta.36 
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: ^2.0.0-beta.36 => 2.0.0-beta.36 
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.36 
    @vuepress/plugin-toc: Not Found
    @vuepress/shared:  2.0.0-beta.35 
    @vuepress/theme-default:  2.0.0-beta.36 
    @vuepress/utils:  2.0.0-beta.35 
    vue:  3.2.31 
    vue-loader: Not Found
    vue-router:  4.0.13 
    vuepress: ^2.0.0-beta.36 => 2.0.0-beta.36 
    vuepress-vite:  2.0.0-beta.36 
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
```
const vue = require("@vitejs/plugin-vue");

module.exports = {
  // ...
  bundlerConfig: {
    viteOptions: {
      plugins: [vue()],
    },
  },
};
```

Remove this and try again.

**Comment by ottopaulsen** [comment]
Thanks a lot. That is correct.
It also helped me narrow down my real problem, and eventually solve it.

Thanks.
