### ISSUE TITLE
[Bug report] Build fails if 'dist' directory points outside of .vuepress folder.

### ISSUE THREAD

**Issue by sebenik** [vuepress/vuepress-next#761]
### Description

Build fails if 'dist' directory points outside of .vuepress folder. 

```
> vuepress-starter@1.0.0 docs:build /tmp/vuepress-starter
> vuepress build docs

info Initializing VuePress and preparing data...
✔ Compiling with vite - done
✖ Rendering pages - failed
Error: Cannot find module 'vue-router'
Require stack:
- /tmp/tmp/.server/app.js
- /tmp/vuepress-starter/node_modules/@vuepress/bundler-vite/lib/build/createBuild.js
- /tmp/vuepress-starter/node_modules/@vuepress/bundler-vite/lib/build/index.js
- /tmp/vuepress-starter/node_modules/@vuepress/bundler-vite/lib/createBundler.js
- /tmp/vuepress-starter/node_modules/@vuepress/bundler-vite/lib/index.js
- /tmp/vuepress-starter/node_modules/@vuepress/core/lib/app/resolveBundler.js
- /tmp/vuepress-starter/node_modules/@vuepress/core/lib/app/createBuildApp.js
- /tmp/vuepress-starter/node_modules/@vuepress/core/lib/app/index.js
- /tmp/vuepress-starter/node_modules/@vuepress/core/lib/index.js
- /tmp/vuepress-starter/node_modules/vuepress/node_modules/vuepress-vite/node_modules/@vuepress/cli/lib/commands/build/createBuild.js
- /tmp/vuepress-starter/node_modules/vuepress/node_modules/vuepress-vite/node_modules/@vuepress/cli/lib/commands/build/index.js
- /tmp/vuepress-starter/node_modules/vuepress/node_modules/vuepress-vite/node_modules/@vuepress/cli/lib/commands/index.js
- /tmp/vuepress-starter/node_modules/vuepress/node_modules/vuepress-vite/node_modules/@vuepress/cli/lib/index.js
- /tmp/vuepress-starter/node_modules/vuepress/node_modules/vuepress-vite/bin/vuepress.js
- /tmp/vuepress-starter/node_modules/vuepress/bin/vuepress.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (/tmp/tmp/.server/app.js:22:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuepress-starter@1.0.0 docs:build: `vuepress build docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuepress-starter@1.0.0 docs:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sebenik/.npm/_logs/2022-03-18T20_27_54_232Z-debug.log
```

### Steps to reproduce

Specify dist folder e.g. `/tmp/dist` in config.js and run build.

### Expected behavior

Build should pass regardless of the folder path as long there are right folder permissions.

### Environment info
Linux
vuepress 2.0.0-beta.36

**Comment by Mister-Hope** [comment]
Duplicated of https://github.com/vuepress/vuepress-next/issues/574
