### ISSUE TITLE
[Bug report] add "externalLinkIcon: false" to themePlugins will break yarn docs:build

### ISSUE THREAD

**Issue by xiaoyunwu** [vuepress/vuepress-next#766]
### Description

Adding "externalLinkIcon: false" to themePlugins will break yarn docs:build

✖ Rendering pages - failed
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/home/sean/src/community/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2737:15)
    at createComponentInstance (/home/sean/src/community/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5598:23)
    at renderComponentVNode (/home/sean/src/community/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:194:22)
    at Object.ssrRenderComponent (/home/sean/src/community/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:626:12)
    at /home/sean/src/community/docs/.vuepress/dist/.server/app.js:38394:32
    at renderComponentSubTree (/home/sean/src/community/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:266:13)
    at renderComponentVNode (/home/sean/src/community/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:211:16)
    at Object.ssrRenderComponent (/home/sean/src/community/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:626:12)
    at /home/sean/src/community/docs/.vuepress/dist/.server/app.js:38624:41
error Command failed with exit code 1.

### Steps to reproduce

- Reproduction link / repo:
https://github.com/framely/community/pull/124/commits/925bece301ca81ae685f25126b0d8742b3a53a3d

### Expected behavior
It should simply work.

### Environment info

- Browser:
- Output of `vuepress info`:

```bash
# Paste output of `vuepress info` here
```

**Comment by xiaoyunwu** [comment]
By the way: mediumZoom:false works, even through this is also in camelCase.

**Comment by xiaoyunwu** [comment]
when will this goes into next release?

**Comment by Mister-Hope** [comment]
快别摸鱼了  @meteorlxy
