### ISSUE TITLE
Package subpath './templates/dev.html' is not defined by "exports"

### ISSUE THREAD

**Issue by dingqianwen** [vuepress/vuepress-next#898]
### Description

Node.js 版本 ：`v14.1.0`

vuepress `2.0.0-beta.39` 升级到 `2.0.0-beta.45` 出现一下异常：

```text
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './templates/dev.html' is not defined by "exports" in /Users/***/vueProjects/***/node_modules/@vuepress/cli/node_modules/@vuepress/client/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1007:27)
    at Function.resolve (internal/modules/cjs/helpers.js:78:19)
```

### Reproduction

https://gitee.com/qwding/my-blog

### Used Package Manager

npm

### System Info

```shell
***@localhost .vuepress % vuepress info

  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.38 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
  Utilities:
    Git: 2.32.1 - /usr/bin/git
  Browsers:
    Chrome: 94.0.4606.71
    Edge: Not Found
    Firefox: 100.0.1
    Safari: 15.4
  npmPackages:
    @vuepress/bundler-vite: Not Found
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli: Not Found
    @vuepress/client: Not Found
    @vuepress/core: Not Found
    @vuepress/markdown: Not Found
    @vuepress/plugin-active-header-links: Not Found
    @vuepress/plugin-back-to-top: Not Found
    @vuepress/plugin-container: Not Found
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon: Not Found
    @vuepress/plugin-git: Not Found
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom: Not Found
    @vuepress/plugin-nprogress: Not Found
    @vuepress/plugin-palette: Not Found
    @vuepress/plugin-prismjs: Not Found
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: Not Found
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data: Not Found
    @vuepress/plugin-toc: Not Found
    @vuepress/shared: Not Found
    @vuepress/theme-default: Not Found
    @vuepress/utils: Not Found
    vue: Not Found
    vue-loader: Not Found
    vue-router: Not Found
    vuepress: Not Found
    vuepress-vite: Not Found
    vuepress-webpack: Not Found
```

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/169023883-21ab445a-50e6-4bee-a751-30f65a1eaa0e.png)

**Comment by dingqianwen** [comment]
> ![image](https://user-images.githubusercontent.com/33315834/169023883-21ab445a-50e6-4bee-a751-30f65a1eaa0e.png)

尝试通过 `git clone https://gitee.com/qwding/my-blog.git` 辛苦了

**Comment by Mister-Hope** [comment]
你一个私有仓库我往哪克隆去.....?

**Comment by dingqianwen** [comment]
> 你一个私有仓库我往哪克隆去.....?

node.js版本从 `v14.1.0` 升级到 `v16.15.0` 正常了，版本太高了

**Comment by Mister-Hope** [comment]
我认为你是存在多个版本的 @vuepress/xxx 你要觉得你自己排查完了也行，反正跟node版本没关系。

**Comment by dingqianwen** [comment]
> x 你要觉得你自己排查完

试过很多方法了已经，缓存清了很多次，删除过很多次，最后这么解决了，不管了，能用就行
