### ISSUE TITLE
Use an external package in umd format to build an error

### ISSUE THREAD

**Issue by xsdream** [vuepress/vuepress-next#917]
### Description

ReferenceError: self is not defined
    at Object.<anonymous> (E:\doron\DL_PORTAL_VUE\dl-vue3\d-comp\node_modules\d-comp\dist\index.js:1:320)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Module.<anonymous> (E:\doron\DL_PORTAL_VUE\dl-vue3\d-comp\docs\.vuepress\.temp\.server\app.js:39:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
error Command failed with exit code 1.

### Reproduction

no reproduction

### Used Package Manager

npm

### System Info

```shell
"vuepress": "^2.0.0-beta.45"
```

**Comment by xsdream** [comment]
Whether it is related to the use of ssr by vuepress?

**Comment by Mister-Hope** [comment]
https://vuejs.org/guide/scaling-up/ssr.html#writing-ssr-friendly-code

**Comment by xsdream** [comment]
@Mister-Hope  thanks

**Comment by xsdream** [comment]
Give it to   has the same problem  people
If you have information about self error, notice "umd" use in webpack
output.globalObject = "this" [webpack]( https://webpack.js.org/configuration/output/#outputlibrarytype)

**Comment by Mister-Hope** [comment]
Yeah, you may have a lot of ways to solve this, including mocking unexisting globals, rewrite globals to exisiting ones (like you said, or just dymaic import them in client only lifecycles.

**Comment by Mister-Hope** [comment]
Also, I would suggest you to open a discussion with these kind of questions next time.

**Comment by xsdream** [comment]
import dcomp  from 'd-comp'

export default defineClientConfig({
    enhance({ app }) {
        app.use(dcomp)
    },
})
code in "docs/.vuepress/client.js"

**Comment by xsdream** [comment]
![image](https://user-images.githubusercontent.com/31870384/171113445-de0583c9-5679-4405-bf8c-5c408996b08e.png)
Can I import dynamically in defineClientConfig's setup?
