### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by Marerc** [vuepress/vuepress-next#992]
### Description

By following https://github.com/vuepress/vuepress-next/issues/328, simple formula can be rendered, but below cannot:

$$\gamma^2_{ace}=max\left[\frac{S_{rare}}{C_{ace}}
\frac{\sum^{10}_{i=1}{{i\left(i-1\right)}}F_i}
{\left(N_{rare}\right)\left(N_{rare}-1\right)} -1,0\right]$$

math text are

```
$$\gamma^2_{ace}=max\left[\frac{S_{rare}}{C_{ace}}
\frac{\sum^{10}_{i=1}{{i\left(i-1\right)}}F_i}
{\left(N_{rare}\right)\left(N_{rare}-1\right)} -1,0\right]$$
```

My config for katex rendering are

```js
const { viteBundler } = require('@vuepress/bundler-vite')
const customElement = [
    "math", "annotation", "semantics",
    "mtext", "mn", "mo", "mi", "mspace",
    "mover", "munder", "munderover", "msup", "msub", "msubsup",
    "mfrac", "mroot", "msqrt",
    "mtable", "mtr", "mtd", "mlabeledtr",
    "mrow", "menclose",
    "mstyle", "mpadded", "mphantom", "mglyph"
];

module.exports = {
    extendsMarkdown: md => {
        md.use(require("markdown-it-katex"))
        md.linkify.set({ fuzzyEmail: false });
    },
    bundler: viteBundler({
        vuePluginOptions: {
            template: {
                compilerOptions: {
                    isCustomElement: tag => customElement.includes(tag)
                }
            }
        }
    }),
```

Even in dev environment, errors occured:

```shell
9:08:25 AM [vite] Internal server error: Error parsing JavaScript expression: Expecting Unicode escape sequence \uXXXX. (1:3)
  Plugin: vite:vue
  File: D:/docsite/docs/.vuepress/.temp/pages/test-permalink.html.vue
  52 |  <p>其中</p>
  53 |  <p><span class="katex-display"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><msubsup><mi>γ</mi><mrow><mi>a</mi><mi>c</mi><mi>e</mi></mrow><mn>2</mn></msubsup><mo>=</mo><mi>m</mi><mi>a</mi><mi>x</mi><mrow><mo fence="true">[</mo><mfrac><mrow><msub><mi>S</mi><mrow><mi>r</mi><mi>a</mi><mi>r</mi><mi>e</mi></mrow></msub></mrow><mrow><msub><mi>C</mi><mrow><mi>a</mi><mi>c</mi><mi>e</mi></mrow></msub></mrow></mfrac><mfrac><mrow><msubsup><mo>∑</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mrow><mn>1</mn><mn>0</mn></mrow></msubsup><mrow><mrow><mi>i</mi><mrow><mo fence="true">(</mo><mi>i</mi><mo>−</mo><mn>1</mn><mo fence="true">)</mo></mrow></mrow></mrow><msub><mi>F</mi><mi>i</mi></msub></mrow><mrow><mrow><mo fence="true">(</mo><msub><mi>N</mi><mrow><mi>r</mi><mi>a</mi><mi>r</mi><mi>e</mi></mrow></msub><mo fence="true">)</mo></mrow><mrow><mo fence="true">(</mo><msub><mi>N</mi><mrow><mi>r</mi><mi>a</mi><mi>r</mi><mi>e</mi></mrow></msub><mo>−</mo><mn>1</mn><mo fence="true">)</mo></mrow></mrow></mfrac><mo>−</mo><mn>1</mn><mo separator="true">,</mo><mn>0</mn><mo fence="true">]</mo></mrow></mrow><annotation encoding="application/x-tex">\gamma^2_{ace}=max\left[\frac{S_{rare}}{C_{ace}}
  54 |  \frac{\sum^{10}_{i=1}{{i\left(i-1\right)}}F_i}
     |                          ^
  55 |  {\left(N_{rare}\right)\left(N_{rare}-1\right)} -1,0\right]</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="strut" style="height:1.505118em;"></span><span class="strut bottom" style="height:2.455148em;vertical-align:-0.95003em;"></span><span class="base displaystyle textstyle uncramped"><span class="mord"><span class="mord mathit" style="margin-right:0.05556em;">γ</span><span class="vlist"><span style="top:0.247em;margin-left:-0.05556em;margin-right:0.05em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle scriptstyle crammped"><span class="mord scriptstyle cramped"><span class="mord mathit">a</span><span class="mord mathit">c</span><span class="mord mathit">e</span></span></span></span><span style="top:-0.4129999999999999em;margin-right:0.05em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle scriptstyle uncramped"><span class="mord maathrm">2</span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span>​</span></span></span><span class="mrel">=</span><span class="mord mathit">m</span><span class="mord mathit">a</sp pan><span class="mord mathit">x</span><span class="minner displaystyle textstyle uncramped"><span class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;"><span class="delimsizing size3">[</span></span><span class="mord reset-textstyle displaystyle textstyle uncramped"><span class="sizing reset-size5 size5 reset-textstyle textstyle uncramped nulldelimiter"></span><span class="mfrac"><span class="vlist"><span style="top:0.686em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle textstyle cramped"><span class="mord textstyle cramped"><span class="mord"><span classs="mord mathit" style="margin-right:0.07153em;">C</span><span class="vlist"><span style="top:0.15em;margin-right:0.05em;margin-left:-0.07153em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textsttyle scriptstyle cramped"><span class="mord scriptstyle cramped"><span class="mord mathit">a</span><span class="mord mathit">c</span><span class="mord mathit">e</span></span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span>​</span></span></span></span></span></span><span style="top:-0.22999999999999998em;">< <span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle textstyle  uncramped frac-line"></span></span><span style="top:-0.677em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle textstyle uncramped"><span class="mord textstyle uncramped"><span class="mordd"><span class="mord mathit" style="margin-right:0.05764em;">S</span><span class="vlist"><span style="top:0.15em;margin-right:0.05em;margin-left:-0.05764em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class=="reset-textstyle scriptstyle cramped"><span class="mord scriptstyle cramped"><span class="mord mathit" style="margin-right:0.02778em;">r</span><span class="mord mathit">a</span><span class="mord mathit" style="margin-right:0.02778em;">r</span><span class="mord mathit">e</span></span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span>​</span></span></span></span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset- -size5 size5"><span style="font-size:0em;">​</span></span>​</span></span></span><span class="sizing reset-size5 size5 reset-textstyl le textstyle uncramped nulldelimiter"></span></span><span class="mord reset-textstyle displaystyle textstyle uncramped"><span class="sizing reset-size5 size5 reset-textstyle textstyle uncramped nulldelimiter"></span><span class="mfrac"><span class="vlist"><span style="top:0.686em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:1em;">​</span></span><span class="resett-textstyle textstyle cramped"><span class="mord textstyle cramped"><span class="minner textstyle cramped"><span class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;">(</span><span class="mord"><span class="mord mathit" style="margin-right:0.10903em;">N</span><span class="vlist"><span style="top:0.15em;margin-right:0.05em;margin-left:-0.10903em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle scriptstyle cramped"><span class="moord scriptstyle cramped"><span class="mord mathit" style="margin-right:0.02778em;">r</span><span class="mord mathit">a</span><span class="mord mathit" style="margin-right:0.02778em;">r</span><span class="mord mathit">e</span></span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span>​</span></span></span><span   class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;">)</span></span><span class="minner textstyle cramped"><span class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;">(</span><span class="mord"><span class="mord mathit" style="margin-right:0.10903em;">N</span><span class="vlist"><span style="top:0.15em;margin-right:0.05em;margin-left:-0.10903em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle scriptstyle crammped"><span class="mord scriptstyle cramped"><span class="mord mathit" style="margin-right:0.02778em;">r</span><span class="mord mathit">a</span><span class="mord mathit" style="margin-right:0.02778em;">r</span><span class="mord mathit">e</span></span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span>​</span> ></span></span><span class="mbin">−</span><span class="mord mathrm">1</span><span class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;">)</span></span></span></span></span><span style="top:-0.2300000000000001em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:1em;">​</span></span><span class="reset-textstyle textstyle uncramped frac-line"></span></sspan><span style="top:-0.69001em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:1em;">​</span></span><spaan class="reset-textstyle textstyle uncramped"><span class="mord textstyle uncramped"><span class="mop"><span class="op-symbol small-op mop" style="top:-0.0000050000000000050004em;">∑</span><span class="vlist"><span style="top:0.30001em;margin-left:0em;margin-right:0.05em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyyle scriptstyle cramped"><span class="mord scriptstyle cramped"><span class="mord mathit">i</span><span class="mrel">=</span><span class="mord mathrm">1</span></span></span></span><span style="top:-0.364em;margin-right:0.05em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle scriptstyle uncramped"><span class="mord scrriptstyle uncramped"><span class="mord mathrm">1</span><span class="mord mathrm">0</span></span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span>​</span></span></span><span class s="mord textstyle uncramped"><span class="mord textstyle uncramped"><span class="mord mathit">i</span><span class="minner textstyle uncramped"><span class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;">(</span><span class="mord mathit">i</span><span class="mbin">−</span><span class="mord mathrm">1</span><span class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;">)</span></span></span></span><span class="mord"><span class="mord mathit" style="margin-right:0.13889em;">F</span><span class="vlist"><span style="top:0.15em;margin-right:0.05em;margin-left:-0.13889em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span><span class="reset-textstyle scriptstyle cramped"><span class="mord mathit">i</span></spaan></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:0em;">​</span></span>​< </span></span></span></span></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:1em;">​</span></span>​</span></span></span><span class="sizing reset-size5 size5 reset-textstyle textstyle uncramped nulld delimiter"></span></span><span class="mbin">−</span><span class="mord mathrm">1</span><span class="mpunct">,</span><span class="mord mathrm">0</span><span class="style-wrap reset-textstyle textstyle uncramped" style="top:0em;"><span class="delimsizing size3">]</span></span></span></span></span></span></span></p>
  56 |  <p><span class="katex-display"><span class="katex"><span class="katex-mathml"><math><semantics><mrow><msub><mi>N</mi><mrow><mi>r</mi><mi>a</mi><mi>r</mi><mi>e</mi></mrow></msub><mo>=</mo><msubsup><mo>∑</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mrow><mi>a</mi><mi>b</mi><mi>u</mi><mi>n</mi><mi>d</mi></mrow></msubsup><mi>i</mi><msub><mi>n</mi><mi>i</mi></msub></mrow><annotation encoding="application/x-tex">N_{rare} = \sum_{i=1}^{abund}in_i
      at createCompilerError (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:19:19)
      at processExpression (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:3486:25)
      at Array.transformExpression (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:3319:24)
      at traverseNode (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2162:41)
      at traverseChildren (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2153:9)
      at traverseNode (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2204:13)
      at traverseChildren (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2153:9)
      at traverseNode (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2204:13)
      at traverseChildren (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2153:9)
      at traverseNode (D:\docsite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2204:13)
```  

### Reproduction

as shown above in description.

### Used Package Manager

npm

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 16.75 GB / 39.77 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Utilities:
    Git: 2.36.0.
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (103.0.1264.44)
  npmPackages:
    @vuepress/bundler-vite: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/bundler-webpack: Not Found
    @vuepress/cli:  2.0.0-beta.49
    @vuepress/client:  2.0.0-beta.49
    @vuepress/core:  2.0.0-beta.49
    @vuepress/markdown:  2.0.0-beta.49
    @vuepress/plugin-active-header-links:  2.0.0-beta.49
    @vuepress/plugin-back-to-top:  2.0.0-beta.49
    @vuepress/plugin-container:  2.0.0-beta.49
    @vuepress/plugin-docsearch: Not Found
    @vuepress/plugin-external-link-icon:  2.0.0-beta.49
    @vuepress/plugin-git:  2.0.0-beta.49
    @vuepress/plugin-google-analytics: Not Found
    @vuepress/plugin-medium-zoom:  2.0.0-beta.49
    @vuepress/plugin-nprogress:  2.0.0-beta.49
    @vuepress/plugin-palette:  2.0.0-beta.49
    @vuepress/plugin-prismjs:  2.0.0-beta.49
    @vuepress/plugin-pwa: Not Found
    @vuepress/plugin-pwa-popup: Not Found
    @vuepress/plugin-register-components: Not Found
    @vuepress/plugin-search: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/plugin-shiki: Not Found
    @vuepress/plugin-theme-data:  2.0.0-beta.49
    @vuepress/plugin-toc: ^2.0.0-beta.49 => 2.0.0-beta.49
    @vuepress/shared:  2.0.0-beta.49
    @vuepress/theme-default:  2.0.0-beta.49
    @vuepress/utils:  2.0.0-beta.49
    vue:  3.2.37
    vue-loader: Not Found
    vue-router:  4.1.2
    vuepress: ^2.0.0-beta.49 => 2.0.0-beta.49
    vuepress-vite:  2.0.0-beta.49
    vuepress-webpack: Not Found
```

**Comment by Marerc** [comment]
It works when I add v-pre in D:\docsite\docs\.vuepress\.temp\pages\test-permalink.html.vue 

``` html
<p><span v-pre class="katex-display"><span class="katex"> ...... <span> <p>
```

But I don't know where to add this tag to the source markdown. If I use `<div v-pre></div>` or `<span v-pre></span>` to wrap the whole formula, that makes whole formula not rendered.

**Comment by meteorlxy** [comment]
Have you tried to wrap the content with extra empty lines?

```md
<div v-pre>
               <----- empty line
formula 
               <----- empty line
</div>
```

**Comment by Marerc** [comment]
Awesome, that is it. Thank you very much. 

> Have you tried to wrap the content with extra empty lines?
> 
> ```lisp
> <div v-pre>
>                <----- empty line
> formula 
>                <----- empty line
> </div>
> ```
